# GMO Forecasting

*Case: Grantham, Mayo, and Van Otterloo, 2012: Estimating the Equity Risk Premium
[9-211-051].*

## 1 READING: GMO

This section is not graded, and you do not need to submit your answers. But you are expected to consider these issues and be ready to discuss them.

1. **GMO’s approach.**
   - Why does GMO believe they can more easily predict **long‑run** than **short‑run** asset‑class performance?

      <span style="color: blue; font-size:0.85em">

      GMO believes that there exists a long-run 'steady state' level to which asset's returns should converge over long time horizons. This belief is founded in a belief in the economics underlying the markets, in which the markets operate in a more efficient manner. In the short run, GMO is aware of the noise that clouds markets and market participants. GMO believes that although things will eventually revert towards the 'steady state', the biases, career considerations, and shocks cause significant noise that make it difficult to predict short-run performance.

      </span>

   - What predicting variables does the case mention are used by GMO? Does this fit with the goal of long‑run forecasts?
      <span style="color: blue; font-size:0.85em">

      GMO uses the dividend yield, the P/E multiple expansion/contraction, the change in the profit margin, and sales growth as its predicting variables. Specifically, it believes that the profit margin and the P/E multiple have long-term steady values, and that in the long-term returns are driven by sales growth and the required dividend yield. This does seem to fit with the goal of long-run forecasts, which are meant to focus on the fundamental drivers of assets, not the market noise.

      </span>

   - How has this approach led to **contrarian** positions?

      <span style="color: blue; font-size:0.85em">

      GMO typically expects the P/E and profit margin to revert to their long-run mean, and adjusts its expectations for dividend yield and sales growth according to their belief in the future of the business cycle. As such, when markets have elevated multiples or profit margins, GMO expects them to contract and thus takes an underweight position.

      </span>

   - How does this approach raise **business risk** and **managerial career risk**?

      <span style="color: blue; font-size:0.85em">

      The first risk, business risk, is a result of a fund needing to secure capital long enough to see its thesis become realized. As a contrarian with a long term perspective, GMO is likely to suffer from severe underperformance while it waits for its thesis to play out. Many investors are not patient enough and may withrdraw their money, leaving GMO with no ability to function at all. Secondly, there is career risk. The risk here is that many investment professionals are driven by their concern for their position, which is largely determined by short(er) term performance. One may be reluctant to stand out if the risk of them, and them alone, being wrong leads to them being fired.

      </span>

2. **The market environment.**
   - We often estimate the market risk premium by looking at a large sample of historic data. What reasons does the case give to be skeptical that the market risk premium will be as high **in the future** as it has been **over the past 50 years**?
      
      <span style="color: blue; font-size:0.85em">
      
      Firstly, we have developed significant infrastructure, theory, and general understanding over the past 50 years. As the process of searching and transacting changes, it is likely that the costs (as reflected in returns) will change as well. In addition, our development of risk-theory is likely to alter the premiums of different assets. From a more foundational perspective, one can not even be sure that the underlying economics functions similarly as it has before. New technology, whether it be the internet or blockchain have proven their ability to alter the intersection of economics and markets (or at least our perspective of such as market participants). Consider GMO's use of profit margins, for example, and how fundamentally different the business models of tech is from prior businesses.

      </span>

   - In 2007, GMO forecasts **real excess equity returns** will be negative. What are the biggest drivers of their **pessimistic conditional** forecast relative to the **unconditional** forecast? (See Exhibit 9.)

      <span style="color: blue; font-size:0.85em">
      
      As of 2007, the market's P/E sat at 19.5 and it's profit margin at 7.9%. These were both above GMO's steady-state levels. Also, GMO forecasted a 2.4% growth in sales as opposed to its 3.2% steady-state level, which seems to indicate that GMO anticipated an economic contraction.

      </span>

   - In the 2011 forecast, what components has GMO revised most relative to 2007? Now how does their conditional forecast compare to the unconditional? (See Exhibit 10.)

      <span style="color: blue; font-size:0.85em">
      
      GMO expects both sales growth and dividend yield to increase from 2011 levels, and expects profit margins to decrease. It has also revised its steady state P/E from 16 down to 15.

      </span>

3. **Consider the asset‑class forecasts in Exhibit 1.**
   - Which asset class did GMO estimate to have a **negative 10‑year return** over 2002–2011?
      
      <span style="color: blue; font-size:0.85em">
      
      GMO expected US equities to have a negative return.

      </span>

   - Which asset classes substantially **outperformed** GMO’s estimate over that time period?
      
      <span style="color: blue; font-size:0.85em">

      Foreign government bonds substantially outperformed GMO's forecast.

      </span>


   - Which asset classes substantially **underperformed** GMO’s estimate over that time period?
      
      <span style="color: blue; font-size:0.85em">

      US Treasuries and US REITS.

      </span>

4. **Fund performance.**
   - In which asset class was **GMWAX** most heavily allocated throughout the majority of 1997–2011?

      <span style="color: blue; font-size:0.85em">

      GMWAX was most heavily positioned in US Fixed Income.

      </span>

   - Comment on the performance of GMWAX versus its benchmark. (No calculation needed; simply comment on the comparison in the exhibits.)

      <span style="color: blue; font-size:0.85em">
      
      GMWAX seems to have performed fairly well in comparison. Most notably, it seemed to have less tail risk on the downside.

      </span>

## 2 Analyzing GMO

_This section utilizes data in the file `gmo_data.xlsx`._ Convert total returns to **excess returns** using the risk‑free rate.

1. **Performance (GMWAX).** Compute **mean**, **volatility**, and **Sharpe ratio** for **GMWAX** over three samples:
   - inception → 2011
   - 2012 → present
   - inception → present  
   Has the mean, vol, and Sharpe changed much since the case?


In [16]:
import pandas as pd
import numpy as np

# Read the Excel file
total_returns = pd.read_excel('gmo_analysis_data.xlsx', sheet_name="total returns", index_col=0)
risk_free_rate = pd.read_excel('gmo_analysis_data.xlsx', sheet_name="risk-free rate", index_col=0)

# Date to datetime
total_returns.index = pd.to_datetime(total_returns.index)
risk_free_rate.index = pd.to_datetime(risk_free_rate.index)


# Calculate excess returns by subtracting risk-free rate from each column
excess_returns = total_returns.sub(risk_free_rate['TBill 3M'], axis=0)

print(excess_returns.head())


                 SPY     GMWAX     GMGEX
date                                    
1996-12-31 -0.075002 -0.073804 -0.064710
1997-01-31  0.010316 -0.036735 -0.017022
1997-02-28 -0.042635 -0.029935 -0.039467
1997-03-31 -0.098941 -0.068372 -0.069661
1997-04-30  0.012038 -0.059061 -0.052330


In [ ]:

# ============================================================================
# 1. Performance (GMWAX): Compute mean, volatility, and Sharpe ratio
# ============================================================================

# Extract GMWAX excess returns
gmwax_excess = excess_returns['GMWAX'].dropna()

# Define time periods
inception_date = gmwax_excess.index.min()
end_2011 = pd.Timestamp('2011-12-31')
start_2012 = pd.Timestamp('2012-01-01')
present_date = gmwax_excess.index.max()

print(f"GMWAX data range: {inception_date.date()} to {present_date.date()}\n")

# Function to calculate statistics
def calculate_stats(returns, period_name):
    """Calculate mean, volatility, and Sharpe ratio for a return series."""
    if len(returns) == 0:
        return None
    
    # Monthly statistics
    mean_monthly = returns.mean()
    vol_monthly = returns.std()
    sharpe_monthly = mean_monthly / vol_monthly if vol_monthly > 0 else np.nan
    
    # Annualize (assuming monthly data)
    mean_annual = mean_monthly * 12
    vol_annual = vol_monthly * np.sqrt(12)
    sharpe_annual = mean_annual / vol_annual if vol_annual > 0 else np.nan
    
    return {
        'Period': period_name,
        'Mean (annualized)': mean_annual,
        'Volatility (annualized)': vol_annual,
        'Sharpe Ratio (annualized)': sharpe_annual,
        'N observations': len(returns)
    }

# Calculate statistics for three periods
# Period 1: inception → 2011
period1 = gmwax_excess[gmwax_excess.index <= end_2011]
stats1 = calculate_stats(period1, 'inception → 2011')

# Period 2: 2012 → present
period2 = gmwax_excess[gmwax_excess.index >= start_2012]
stats2 = calculate_stats(period2, '2012 → present')

# Period 3: inception → present
period3 = gmwax_excess
stats3 = calculate_stats(period3, 'inception → present')

# Create results DataFrame
results = pd.DataFrame([stats1, stats2, stats3])

print("="*80)
print("GMWAX Performance Statistics")
print("="*80)
print(results.to_string(index=False))

# Display comparison
print("\n" + "="*80)
print("Comparison: Has performance changed since the case?")
print("="*80)
if stats1 and stats2:
    print(f"\nMean Return (annualized):")
    print(f"  Inception → 2011: {stats1['Mean (annualized)']:.4f} ({stats1['Mean (annualized)']*100:.2f}%)")
    print(f"  2012 → present:   {stats2['Mean (annualized)']:.4f} ({stats2['Mean (annualized)']*100:.2f}%)")
    mean_change = stats2['Mean (annualized)'] - stats1['Mean (annualized)']
    print(f"  Change:           {mean_change:+.4f} ({mean_change*100:+.2f}%)")
    
    print(f"\nVolatility (annualized):")
    print(f"  Inception → 2011: {stats1['Volatility (annualized)']:.4f} ({stats1['Volatility (annualized)']*100:.2f}%)")
    print(f"  2012 → present:   {stats2['Volatility (annualized)']:.4f} ({stats2['Volatility (annualized)']*100:.2f}%)")
    vol_change = stats2['Volatility (annualized)'] - stats1['Volatility (annualized)']
    print(f"  Change:           {vol_change:+.4f} ({vol_change*100:+.2f}%)")
    
    print(f"\nSharpe Ratio (annualized):")
    print(f"  Inception → 2011: {stats1['Sharpe Ratio (annualized)']:.4f}")
    print(f"  2012 → present:   {stats2['Sharpe Ratio (annualized)']:.4f}")
    sharpe_change = stats2['Sharpe Ratio (annualized)'] - stats1['Sharpe Ratio (annualized)']
    print(f"  Change:           {sharpe_change:+.4f}")
    

GMWAX data range: 1996-12-31 to 2025-10-31

GMWAX Performance Statistics
             Period  Mean (annualized)  Volatility (annualized)  Sharpe Ratio (annualized)  N observations
   inception → 2011          -0.265291                 0.131867                  -2.011809             181
     2012 → present          -0.123303                 0.109588                  -1.125154             166
inception → present          -0.197366                 0.123263                  -1.601179             347

Comparison: Has performance changed since the case?

Mean Return (annualized):
  Inception → 2011: -0.2653 (-26.53%)
  2012 → present:   -0.1233 (-12.33%)
  Change:           +0.1420 (+14.20%)

Volatility (annualized):
  Inception → 2011: 0.1319 (13.19%)
  2012 → present:   0.1096 (10.96%)
  Change:           -0.0223 (-2.23%)

Sharpe Ratio (annualized):
  Inception → 2011: -2.0118
  2012 → present:   -1.1252
  Change:           +0.8867



<span style="color: blue; font-size:0.85em">

Performance improved since 2011, but remains negative.

Mean return: Improved from -26.53% to -12.33% (14.20 percentage points)

Volatility: Decreased from 13.19% to 10.96%

Sharpe ratio: Improved from -2.01 to -1.13

Interpretation: Risk-adjusted returns are less negative, indicating a more stable profile

</span>


2. **Tail risk (GMWAX).** For all three samples, analyze extreme scenarios:
   - minimum return
   - 5th percentile (VaR‑5th)
   - maximum drawdown (compute on **total** returns, not excess returns)  
   (a) Does GMWAX have high or low tail‑risk as seen by these stats?  
   (b) Does that vary much across the two subsamples?


In [ ]:
# ============================================================================
# 2. Tail risk (GMWAX): Analyze extreme scenarios
# ============================================================================

# Extract GMWAX total returns (not excess returns for drawdown calculation)
gmwax_total = total_returns['GMWAX'].dropna()

# Define time periods
inception_date = gmwax_total.index.min()
end_2011 = pd.Timestamp('2011-12-31')
start_2012 = pd.Timestamp('2012-01-01')
present_date = gmwax_total.index.max()

print(f"GMWAX data range: {inception_date.date()} to {present_date.date()}\n")

# Function to calculate maximum drawdown
def calculate_max_drawdown(returns):
    """Calculate maximum drawdown from a return series."""
    # Convert returns to cumulative wealth (starting at 1)
    cumulative = (1 + returns).cumprod()
    
    # Calculate running maximum
    running_max = cumulative.expanding().max()
    
    # Calculate drawdown
    drawdown = (cumulative - running_max) / running_max
    
    # Maximum drawdown is the minimum (most negative) drawdown
    max_dd = drawdown.min()
    
    return max_dd

# Function to calculate tail risk statistics
def calculate_tail_risk(returns, period_name):
    """Calculate tail risk statistics for a return series."""
    if len(returns) == 0:
        return None
    
    min_return = returns.min()
    var_5th = returns.quantile(0.05)  # 5th percentile (VaR-5th)
    max_drawdown = calculate_max_drawdown(returns)
    
    return {
        'Period': period_name,
        'Minimum Return': min_return,
        '5th Percentile (VaR-5th)': var_5th,
        'Maximum Drawdown': max_drawdown,
        'N observations': len(returns)
    }

# Calculate tail risk statistics for three periods
# Period 1: inception → 2011
period1 = gmwax_total[gmwax_total.index <= end_2011]
tail1 = calculate_tail_risk(period1, 'inception → 2011')

# Period 2: 2012 → present
period2 = gmwax_total[gmwax_total.index >= start_2012]
tail2 = calculate_tail_risk(period2, '2012 → present')

# Period 3: inception → present
period3 = gmwax_total
tail3 = calculate_tail_risk(period3, 'inception → present')

# Create results DataFrame
tail_results = pd.DataFrame([tail1, tail2, tail3])

print("="*80)
print("GMWAX Tail Risk Statistics")
print("="*80)
print(tail_results.to_string(index=False))

# Display comparison
print("\n" + "="*80)
print("Comparison: Tail Risk Analysis")
print("="*80)
if tail1 and tail2:
    print(f"\nMinimum Return:")
    print(f"  Inception → 2011: {tail1['Minimum Return']:.4f} ({tail1['Minimum Return']*100:.2f}%)")
    print(f"  2012 → present:   {tail2['Minimum Return']:.4f} ({tail2['Minimum Return']*100:.2f}%)")
    min_change = tail2['Minimum Return'] - tail1['Minimum Return']
    print(f"  Change:           {min_change:+.4f} ({min_change*100:+.2f}%)")
    
    print(f"\n5th Percentile (VaR-5th):")
    print(f"  Inception → 2011: {tail1['5th Percentile (VaR-5th)']:.4f} ({tail1['5th Percentile (VaR-5th)']*100:.2f}%)")
    print(f"  2012 → present:   {tail2['5th Percentile (VaR-5th)']:.4f} ({tail2['5th Percentile (VaR-5th)']*100:.2f}%)")
    var_change = tail2['5th Percentile (VaR-5th)'] - tail1['5th Percentile (VaR-5th)']
    print(f"  Change:           {var_change:+.4f} ({var_change*100:+.2f}%)")
    
    print(f"\nMaximum Drawdown:")
    print(f"  Inception → 2011: {tail1['Maximum Drawdown']:.4f} ({tail1['Maximum Drawdown']*100:.2f}%)")
    print(f"  2012 → present:   {tail2['Maximum Drawdown']:.4f} ({tail2['Maximum Drawdown']*100:.2f}%)")
    dd_change = tail2['Maximum Drawdown'] - tail1['Maximum Drawdown']
    print(f"  Change:           {dd_change:+.4f} ({dd_change*100:+.2f}%)")

GMWAX data range: 1996-12-31 to 2025-10-31

GMWAX Tail Risk Statistics
             Period  Minimum Return  5th Percentile (VaR-5th)  Maximum Drawdown  N observations
   inception → 2011       -0.145129                 -0.043986         -0.293614             181
     2012 → present       -0.114967                 -0.036928         -0.216795             166
inception → present       -0.145129                 -0.040369         -0.293614             347

Comparison: Tail Risk Analysis

Minimum Return:
  Inception → 2011: -0.1451 (-14.51%)
  2012 → present:   -0.1150 (-11.50%)
  Change:           +0.0302 (+3.02%)

5th Percentile (VaR-5th):
  Inception → 2011: -0.0440 (-4.40%)
  2012 → present:   -0.0369 (-3.69%)
  Change:           +0.0071 (+0.71%)

Maximum Drawdown:
  Inception → 2011: -0.2936 (-29.36%)
  2012 → present:   -0.2168 (-21.68%)
  Change:           +0.0768 (+7.68%)


(a) Does GMWAX have high or low tail-risk?
   
   <span style="color: blue; font-size:0.85em">

   GMWAX exhibits HIGH tail-risk, with significant potential for large losses.

   Average 5th percentile loss: -4.05%

   Average maximum drawdown: 25.52%

   </span>

(b) Does tail-risk vary much across the two subsamples?
   
   <span style="color: blue; font-size:0.85em">

   Tail-risk has changed significantly across subsamples.

   The 5th percentile loss is less severe in the post-2011 period.
   
   Maximum drawdown is smaller in the post-2011 period.

   </span>


3. **Market exposure (GMWAX).** For all three samples, regress **excess returns of GMWAX** on **excess returns of SPY**:
   - report estimated **alpha**, **beta**, and **R²**


In [26]:
# ============================================================================
# 3. Market exposure (GMWAX): Regress excess returns on SPY excess returns
# ============================================================================

from sklearn.linear_model import LinearRegression
from scipy import stats

# Extract excess returns for GMWAX and SPY
gmwax_excess = excess_returns['GMWAX'].dropna()
spy_excess = excess_returns['SPY'].dropna()

# Align the indices
common_idx = gmwax_excess.index.intersection(spy_excess.index)
gmwax_excess = gmwax_excess.loc[common_idx]
spy_excess = spy_excess.loc[common_idx]

# Define time periods
inception_date = gmwax_excess.index.min()
end_2011 = pd.Timestamp('2011-12-31')
start_2012 = pd.Timestamp('2012-01-01')
present_date = gmwax_excess.index.max()

print(f"Data range: {inception_date.date()} to {present_date.date()}\n")

# Function to perform regression and return statistics
def regress_gmwax_on_spy(gmwax_ret, spy_ret, period_name):
    """Regress GMWAX excess returns on SPY excess returns."""
    if len(gmwax_ret) == 0 or len(spy_ret) == 0:
        return None
    
    # Align indices
    common_idx = gmwax_ret.index.intersection(spy_ret.index)
    gmwax_aligned = gmwax_ret.loc[common_idx]
    spy_aligned = spy_ret.loc[common_idx]
    
    # Prepare data for regression (X = SPY, y = GMWAX)
    X = spy_aligned.values.reshape(-1, 1)
    y = gmwax_aligned.values
    
    # Perform OLS regression
    reg = LinearRegression()
    reg.fit(X, y)
    
    # Get predictions
    y_pred = reg.predict(X)
    
    # Calculate R-squared
    ss_res = np.sum((y - y_pred) ** 2)
    ss_tot = np.sum((y - np.mean(y)) ** 2)
    r_squared = 1 - (ss_res / ss_tot) if ss_tot != 0 else 0
    
    # Calculate standard errors and t-statistics
    n = len(y)
    residuals = y - y_pred
    mse = np.sum(residuals ** 2) / (n - 2)  # Mean squared error
    
    # Standard errors
    x_mean = np.mean(X)
    sxx = np.sum((X.flatten() - x_mean) ** 2)
    se_beta = np.sqrt(mse / sxx) if sxx != 0 else np.nan
    se_alpha = np.sqrt(mse * (1/n + x_mean**2 / sxx)) if sxx != 0 else np.nan
    
    # t-statistics
    t_alpha = reg.intercept_ / se_alpha if se_alpha != 0 else np.nan
    t_beta = reg.coef_[0] / se_beta if se_beta != 0 else np.nan
    
    return {
        'Period': period_name,
        'Alpha': reg.intercept_,
        'Beta': reg.coef_[0],
        'R²': r_squared,
        'Alpha (t-stat)': t_alpha,
        'Beta (t-stat)': t_beta,
        'N observations': n
    }

# Perform regressions for three periods
# Period 1: inception → 2011
period1_gmwax = gmwax_excess[gmwax_excess.index <= end_2011]
period1_spy = spy_excess[spy_excess.index <= end_2011]
reg1 = regress_gmwax_on_spy(period1_gmwax, period1_spy, 'inception → 2011')

# Period 2: 2012 → present
period2_gmwax = gmwax_excess[gmwax_excess.index >= start_2012]
period2_spy = spy_excess[spy_excess.index >= start_2012]
reg2 = regress_gmwax_on_spy(period2_gmwax, period2_spy, '2012 → present')

# Period 3: inception → present
period3_gmwax = gmwax_excess
period3_spy = spy_excess
reg3 = regress_gmwax_on_spy(period3_gmwax, period3_spy, 'inception → present')

# Create results DataFrame
reg_results = pd.DataFrame([reg1, reg2, reg3])

print("="*80)
print("GMWAX Market Exposure (Regression on SPY)")
print("="*80)
print(reg_results.to_string(index=False))

# Display comparison
print("\n" + "="*80)
print("Comparison: Market Exposure Analysis")
print("="*80)
if reg1 and reg2:
    print(f"\nAlpha (monthly):")
    print(f"  Inception → 2011: {reg1['Alpha']:.6f} (t-stat: {reg1['Alpha (t-stat)']:.2f})")
    print(f"  2012 → present:   {reg2['Alpha']:.6f} (t-stat: {reg2['Alpha (t-stat)']:.2f})")
    alpha_change = reg2['Alpha'] - reg1['Alpha']
    print(f"  Change:           {alpha_change:+.6f}")
    
    print(f"\nBeta:")
    print(f"  Inception → 2011: {reg1['Beta']:.4f} (t-stat: {reg1['Beta (t-stat)']:.2f})")
    print(f"  2012 → present:   {reg2['Beta']:.4f} (t-stat: {reg2['Beta (t-stat)']:.2f})")
    beta_change = reg2['Beta'] - reg1['Beta']
    print(f"  Change:           {beta_change:+.4f}")
    
    print(f"\nR²:")
    print(f"  Inception → 2011: {reg1['R²']:.4f}")
    print(f"  2012 → present:   {reg2['R²']:.4f}")
    r2_change = reg2['R²'] - reg1['R²']
    print(f"  Change:           {r2_change:+.4f}")


Data range: 1996-12-31 to 2025-10-31

GMWAX Market Exposure (Regression on SPY)
             Period     Alpha     Beta       R²  Alpha (t-stat)  Beta (t-stat)  N observations
   inception → 2011 -0.007864 0.619535 0.687802       -4.519375      19.858328             181
     2012 → present -0.008309 0.629431 0.769300       -7.006386      23.385467             166
inception → present -0.008053 0.622398 0.727059       -7.765373      30.315185             347

Comparison: Market Exposure Analysis

Alpha (monthly):
  Inception → 2011: -0.007864 (t-stat: -4.52)
  2012 → present:   -0.008309 (t-stat: -7.01)
  Change:           -0.000445

Beta:
  Inception → 2011: 0.6195 (t-stat: 19.86)
  2012 → present:   0.6294 (t-stat: 23.39)
  Change:           +0.0099

R²:
  Inception → 2011: 0.6878
  2012 → present:   0.7693
  Change:           +0.0815



   - is GMWAX a **low‑beta** strategy? has that changed since the case?
   
      <span style="color: blue; font-size:0.85em">

      Yes, GMWAX is a low-beta strategy. Beta is 0.6195 (inception → 2011) and 0.6294 (2012 → present), both below 1.0, indicating lower market sensitivity than the S&P 500. The change of +0.0099 is small, so beta has remained stable. The strategy has maintained its low-beta profile.

      </span>

   - does GMWAX provide **alpha**? has that changed across subsamples?

      <span style="color: blue; font-size:0.85em">

      No, GMWAX does not provide positive alpha. Both periods show statistically significant negative alpha:
   
      Inception → 2011: -0.007864 monthly (t-stat: -4.52)
   
      2012 → present: -0.008309 monthly (t-stat: -7.01)
   
      The alpha became slightly more negative (change: -0.000445), so risk-adjusted performance has deteriorated. The negative alpha is statistically significant in both periods, indicating consistent underperformance relative to the market after controlling for beta exposure.

      </span>



4. **Compare to GMGEX.** Repeat items 1–3 for **GMGEX**. What are key differences between the two strategies?

In [28]:
# ============================================================================
# 4. Compare to GMGEX: Repeat items 1-3 for GMGEX
# ============================================================================

print("="*80)
print("GMGEX ANALYSIS - Repeating Items 1-3")
print("="*80)

# ============================================================================
# Item 1: Performance (GMGEX) - Mean, Volatility, Sharpe Ratio
# ============================================================================

# Extract GMGEX excess returns
gmgex_excess = excess_returns['GMGEX'].dropna()

# Define time periods
inception_date_gmgex = gmgex_excess.index.min()
end_2011 = pd.Timestamp('2011-12-31')
start_2012 = pd.Timestamp('2012-01-01')
present_date_gmgex = gmgex_excess.index.max()

print(f"\nGMGEX data range: {inception_date_gmgex.date()} to {present_date_gmgex.date()}\n")

# Function to calculate statistics (reuse from earlier)
def calculate_stats(returns, period_name):
    """Calculate mean, volatility, and Sharpe ratio for a return series."""
    if len(returns) == 0:
        return None
    
    mean_monthly = returns.mean()
    vol_monthly = returns.std()
    sharpe_monthly = mean_monthly / vol_monthly if vol_monthly > 0 else np.nan
    
    # Annualize (assuming monthly data)
    mean_annual = mean_monthly * 12
    vol_annual = vol_monthly * np.sqrt(12)
    sharpe_annual = mean_annual / vol_annual if vol_annual > 0 else np.nan
    
    return {
        'Period': period_name,
        'Mean (annualized)': mean_annual,
        'Volatility (annualized)': vol_annual,
        'Sharpe Ratio (annualized)': sharpe_annual,
        'N observations': len(returns)
    }

# Calculate statistics for three periods
period1_gmgex = gmgex_excess[gmgex_excess.index <= end_2011]
period2_gmgex = gmgex_excess[gmgex_excess.index >= start_2012]
period3_gmgex = gmgex_excess

stats1_gmgex = calculate_stats(period1_gmgex, 'inception → 2011')
stats2_gmgex = calculate_stats(period2_gmgex, '2012 → present')
stats3_gmgex = calculate_stats(period3_gmgex, 'inception → present')

gmgex_perf_results = pd.DataFrame([stats1_gmgex, stats2_gmgex, stats3_gmgex])

print("\n" + "="*80)
print("1. GMGEX Performance Statistics")
print("="*80)
print(gmgex_perf_results.to_string(index=False))

# ============================================================================
# Item 2: Tail Risk (GMGEX) - Minimum, VaR-5th, Maximum Drawdown
# ============================================================================

# Extract GMGEX total returns (for drawdown calculation)
gmgex_total = total_returns['GMGEX'].dropna()

# Function to calculate maximum drawdown (reuse from earlier)
def calculate_max_drawdown(returns):
    """Calculate maximum drawdown from a return series."""
    cumulative = (1 + returns).cumprod()
    running_max = cumulative.expanding().max()
    drawdown = (cumulative - running_max) / running_max
    return drawdown.min()

# Function to calculate tail risk statistics
def calculate_tail_risk(returns, period_name):
    """Calculate tail risk statistics for a return series."""
    if len(returns) == 0:
        return None
    
    min_return = returns.min()
    var_5th = returns.quantile(0.05)
    max_drawdown = calculate_max_drawdown(returns)
    
    return {
        'Period': period_name,
        'Minimum Return': min_return,
        '5th Percentile (VaR-5th)': var_5th,
        'Maximum Drawdown': max_drawdown,
        'N observations': len(returns)
    }

# Calculate tail risk for three periods
period1_gmgex_total = gmgex_total[gmgex_total.index <= end_2011]
period2_gmgex_total = gmgex_total[gmgex_total.index >= start_2012]
period3_gmgex_total = gmgex_total

tail1_gmgex = calculate_tail_risk(period1_gmgex_total, 'inception → 2011')
tail2_gmgex = calculate_tail_risk(period2_gmgex_total, '2012 → present')
tail3_gmgex = calculate_tail_risk(period3_gmgex_total, 'inception → present')

gmgex_tail_results = pd.DataFrame([tail1_gmgex, tail2_gmgex, tail3_gmgex])

print("\n" + "="*80)
print("2. GMGEX Tail Risk Statistics")
print("="*80)
print(gmgex_tail_results.to_string(index=False))

# ============================================================================
# Item 3: Market Exposure (GMGEX) - Regression on SPY
# ============================================================================

# Extract SPY excess returns (already have from earlier)
spy_excess = excess_returns['SPY'].dropna()

# Align indices
common_idx_gmgex = gmgex_excess.index.intersection(spy_excess.index)
gmgex_excess_aligned = gmgex_excess.loc[common_idx_gmgex]
spy_excess_aligned = spy_excess.loc[common_idx_gmgex]

# Function to perform regression (reuse from earlier)
def regress_on_spy(fund_ret, spy_ret, period_name):
    """Regress fund excess returns on SPY excess returns."""
    if len(fund_ret) == 0 or len(spy_ret) == 0:
        return None
    
    common_idx = fund_ret.index.intersection(spy_ret.index)
    fund_aligned = fund_ret.loc[common_idx]
    spy_aligned = spy_ret.loc[common_idx]
    
    X = spy_aligned.values.reshape(-1, 1)
    y = fund_aligned.values
    
    reg = LinearRegression()
    reg.fit(X, y)
    
    y_pred = reg.predict(X)
    ss_res = np.sum((y - y_pred) ** 2)
    ss_tot = np.sum((y - np.mean(y)) ** 2)
    r_squared = 1 - (ss_res / ss_tot) if ss_tot != 0 else 0
    
    n = len(y)
    residuals = y - y_pred
    mse = np.sum(residuals ** 2) / (n - 2)
    
    x_mean = np.mean(X)
    sxx = np.sum((X.flatten() - x_mean) ** 2)
    se_beta = np.sqrt(mse / sxx) if sxx != 0 else np.nan
    se_alpha = np.sqrt(mse * (1/n + x_mean**2 / sxx)) if sxx != 0 else np.nan
    
    t_alpha = reg.intercept_ / se_alpha if se_alpha != 0 else np.nan
    t_beta = reg.coef_[0] / se_beta if se_beta != 0 else np.nan
    
    return {
        'Period': period_name,
        'Alpha': reg.intercept_,
        'Beta': reg.coef_[0],
        'R²': r_squared,
        'Alpha (t-stat)': t_alpha,
        'Beta (t-stat)': t_beta,
        'N observations': n
    }

# Perform regressions for three periods
period1_gmgex_reg = gmgex_excess_aligned[gmgex_excess_aligned.index <= end_2011]
period1_spy_reg = spy_excess_aligned[spy_excess_aligned.index <= end_2011]

period2_gmgex_reg = gmgex_excess_aligned[gmgex_excess_aligned.index >= start_2012]
period2_spy_reg = spy_excess_aligned[spy_excess_aligned.index >= start_2012]

reg1_gmgex = regress_on_spy(period1_gmgex_reg, period1_spy_reg, 'inception → 2011')
reg2_gmgex = regress_on_spy(period2_gmgex_reg, period2_spy_reg, '2012 → present')
reg3_gmgex = regress_on_spy(gmgex_excess_aligned, spy_excess_aligned, 'inception → present')

gmgex_reg_results = pd.DataFrame([reg1_gmgex, reg2_gmgex, reg3_gmgex])

print("\n" + "="*80)
print("3. GMGEX Market Exposure (Regression on SPY)")
print("="*80)
print(gmgex_reg_results.to_string(index=False))



GMGEX ANALYSIS - Repeating Items 1-3

GMGEX data range: 1996-12-31 to 2025-10-31


1. GMGEX Performance Statistics
             Period  Mean (annualized)  Volatility (annualized)  Sharpe Ratio (annualized)  N observations
   inception → 2011          -0.315536                 0.164479                  -1.918397             181
     2012 → present          -0.159278                 0.231652                  -0.687575             166
inception → present          -0.240784                 0.200434                  -1.201316             347

2. GMGEX Tail Risk Statistics
             Period  Minimum Return  5th Percentile (VaR-5th)  Maximum Drawdown  N observations
   inception → 2011       -0.151229                 -0.079652         -0.555630             181
     2012 → present       -0.658652                 -0.065289         -0.737364             166
inception → present       -0.658652                 -0.075243         -0.761812             347

3. GMGEX Market Exposure (Regression on S

### COMPARISON: GMWAX vs GMGEX - Key Differences

<span style="color: blue; font-size:0.85em">

1. PERFORMANCE COMPARISON (Inception → Present):

GMGEX - Mean: -0.2408 (-24.08%)

GMGEX - Volatility: 0.2004 (20.04%)

GMGEX - Sharpe: -1.2013

Note: Compare with GMWAX results from earlier analysis

2. TAIL RISK COMPARISON (Inception → Present):

GMGEX - Minimum Return: -0.6587 (-65.87%)

GMGEX - 5th Percentile (VaR-5th): -0.0752 (-7.52%)

GMGEX - Maximum Drawdown: -0.7618 (-76.18%)

Note: Compare with GMWAX tail risk results from earlier analysis

3. MARKET EXPOSURE COMPARISON (Inception → Present):

GMGEX - Alpha: -0.009222 (t-stat: -3.88)

GMGEX - Beta: 0.8040 (t-stat: 17.10)

GMGEX - R²: 0.4588

Note: Compare with GMWAX regression results from earlier analysis


To identify key differences, compare:
  - Performance metrics (mean, volatility, Sharpe) between GMWAX and GMGEX
  - Tail risk metrics (min return, VaR-5th, max drawdown)
  - Market exposure (alpha, beta, R²)

Key questions to consider:
  1. Which fund has better risk-adjusted returns (Sharpe ratio)?
  2. Which fund has lower tail risk?
  3. Which fund has lower market exposure (beta)?
  4. Which fund provides better alpha (or less negative alpha)?
  5. Which fund has higher R² (more market-driven vs idiosyncratic)?

## 3 Forecast Regressions

_This section utilizes data in `gmo_data.xlsx`._

1. **Lagged regression.** Consider the regression with predictors lagged one period:

$$
r^{SPY}_{t} \;=\; \alpha^{SPY,X} \;+\; \big(\beta^{SPY,X}\big)^\prime X_{t-1} \;+\; \epsilon^{SPY,X}_{t}
\tag{1}
$$

Estimate (1) and report the **$R^2$**, as well as the OLS estimates for $\alpha$ and $\beta$. Do this for:
   - $X$ as a single regressor, the **dividend–price** ratio ($DP$)
   - $X$ as a single regressor, the **earnings–price** ratio ($EP$)
   - $X$ with **three** regressors: $DP$, $EP$, and the **10‑year yield**  
   For each, report the **$R^2$**.


In [31]:
signals = pd.read_excel('gmo_analysis_data.xlsx', sheet_name="signals", index_col=0)
signals.head()

SPX D/P   SPX E/P  T-Note 10YR
date                                       
1996-12-31  0.019651  0.051592      0.06418
1997-01-31  0.018455  0.048704      0.06494
1997-02-28  0.018502  0.048434      0.06552
1997-03-31  0.019427  0.055559      0.06903
1997-04-30  0.018430  0.052318      0.06718

In [32]:
# ============================================================================
# 3. Forecast Regressions - Lagged Regression
# r^SPY_t = α + β'X_{t-1} + ε_t
# ============================================================================

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# Get SPY excess returns (dependent variable)
spy_excess = excess_returns['SPY'].dropna()

# Ensure signals index is datetime
signals.index = pd.to_datetime(signals.index)

# Define predictor columns
dp_col = 'SPX D/P'  # Dividend-price ratio
ep_col = 'SPX E/P'  # Earnings-price ratio
yield_col = 'T-Note 10YR'  # 10-year yield

print("="*80)
print("LAGGED REGRESSION: r^SPY_t = α + β'X_{t-1} + ε_t")
print("="*80)
print(f"\nDependent variable: SPY excess returns")
print(f"Predictors: {dp_col}, {ep_col}, {yield_col}")
print(f"\nData ranges:")
print(f"  SPY excess returns: {spy_excess.index.min().date()} to {spy_excess.index.max().date()}")
print(f"  Signals: {signals.index.min().date()} to {signals.index.max().date()}")

# Function to perform lagged regression
def lagged_regression(y, X, X_names):
    """
    Perform lagged regression: y_t = α + β'X_{t-1} + ε_t
    
    Parameters:
    y: Series of dependent variable (SPY returns at time t)
    X: DataFrame of predictors (at time t-1)
    X_names: List of predictor names
    
    Returns:
    Dictionary with alpha, beta, R², and other statistics
    """
    # Align indices - y at time t, X at time t-1
    # We need to shift X forward by 1 period so X[t-1] aligns with y[t]
    X_lagged = X[X_names].shift(1)  # Shift forward so X[t-1] aligns with y[t]
    
    # Align indices
    common_idx = y.index.intersection(X_lagged.index)
    y_aligned = y.loc[common_idx]
    X_aligned = X_lagged.loc[common_idx]
    
    # Drop rows with NaN (from the lag)
    valid_mask = ~(X_aligned.isna().any(axis=1) | y_aligned.isna())
    y_clean = y_aligned[valid_mask]
    X_clean = X_aligned[valid_mask]
    
    if len(y_clean) == 0:
        return None
    
    # Prepare data for regression
    X_values = X_clean.values
    y_values = y_clean.values
    
    # Perform OLS regression
    reg = LinearRegression()
    reg.fit(X_values, y_values)
    
    # Get predictions
    y_pred = reg.predict(X_values)
    
    # Calculate R-squared
    r_squared = r2_score(y_values, y_pred)
    
    # Calculate standard errors and t-statistics
    n = len(y_values)
    k = X_values.shape[1]  # number of predictors
    residuals = y_values - y_pred
    mse = np.sum(residuals ** 2) / (n - k - 1)  # Mean squared error
    
    # Standard errors
    X_with_const = np.column_stack([np.ones(n), X_values])
    try:
        cov_matrix = mse * np.linalg.inv(X_with_const.T @ X_with_const)
        se = np.sqrt(np.diag(cov_matrix))
        se_alpha = se[0]
        se_beta = se[1:]
    except:
        se_alpha = np.nan
        se_beta = np.full(k, np.nan)
    
    # t-statistics
    t_alpha = reg.intercept_ / se_alpha if se_alpha != 0 and not np.isnan(se_alpha) else np.nan
    t_beta = reg.coef_ / se_beta if not np.isnan(se_beta).any() else np.full(k, np.nan)
    
    # Create beta dictionary
    beta_dict = {name: coef for name, coef in zip(X_names, reg.coef_)}
    t_beta_dict = {name: t for name, t in zip(X_names, t_beta)}
    
    return {
        'Alpha': reg.intercept_,
        'Beta': beta_dict,
        'R²': r_squared,
        'Alpha (t-stat)': t_alpha,
        'Beta (t-stat)': t_beta_dict,
        'N observations': n
    }

# ============================================================================
# Regression 1: DP only
# ============================================================================
print("\n" + "="*80)
print("1. Regression with DP (dividend-price ratio) only")
print("="*80)
reg1 = lagged_regression(spy_excess, signals, [dp_col])
if reg1:
    print(f"Alpha: {reg1['Alpha']:.6f} (t-stat: {reg1['Alpha (t-stat)']:.4f})")
    print(f"Beta ({dp_col}): {reg1['Beta'][dp_col]:.6f} (t-stat: {reg1['Beta (t-stat)'][dp_col]:.4f})")
    print(f"R²: {reg1['R²']:.6f}")
    print(f"N observations: {reg1['N observations']}")
else:
    print("Regression failed - check data alignment")

# ============================================================================
# Regression 2: EP only
# ============================================================================
print("\n" + "="*80)
print("2. Regression with EP (earnings-price ratio) only")
print("="*80)
reg2 = lagged_regression(spy_excess, signals, [ep_col])
if reg2:
    print(f"Alpha: {reg2['Alpha']:.6f} (t-stat: {reg2['Alpha (t-stat)']:.4f})")
    print(f"Beta ({ep_col}): {reg2['Beta'][ep_col]:.6f} (t-stat: {reg2['Beta (t-stat)'][ep_col]:.4f})")
    print(f"R²: {reg2['R²']:.6f}")
    print(f"N observations: {reg2['N observations']}")
else:
    print("Regression failed - check data alignment")

# ============================================================================
# Regression 3: DP, EP, and 10-year yield
# ============================================================================
print("\n" + "="*80)
print("3. Regression with DP, EP, and 10-year yield")
print("="*80)
reg3 = lagged_regression(spy_excess, signals, [dp_col, ep_col, yield_col])
if reg3:
    print(f"Alpha: {reg3['Alpha']:.6f} (t-stat: {reg3['Alpha (t-stat)']:.4f})")
    print(f"Beta ({dp_col}): {reg3['Beta'][dp_col]:.6f} (t-stat: {reg3['Beta (t-stat)'][dp_col]:.4f})")
    print(f"Beta ({ep_col}): {reg3['Beta'][ep_col]:.6f} (t-stat: {reg3['Beta (t-stat)'][ep_col]:.4f})")
    print(f"Beta ({yield_col}): {reg3['Beta'][yield_col]:.6f} (t-stat: {reg3['Beta (t-stat)'][yield_col]:.4f})")
    print(f"R²: {reg3['R²']:.6f}")
    print(f"N observations: {reg3['N observations']}")
else:
    print("Regression failed - check data alignment")

# ============================================================================
# Summary Table
# ============================================================================
print("\n" + "="*80)
print("SUMMARY TABLE")
print("="*80)
summary_data = []
if reg1:
    summary_data.append({
        'Model': 'DP only',
        'Alpha': reg1['Alpha'],
        'Beta_DP': reg1['Beta'][dp_col],
        'R²': reg1['R²']
    })
if reg2:
    summary_data.append({
        'Model': 'EP only',
        'Alpha': reg2['Alpha'],
        'Beta_EP': reg2['Beta'][ep_col],
        'R²': reg2['R²']
    })
if reg3:
    summary_data.append({
        'Model': 'DP, EP, 10Y Yield',
        'Alpha': reg3['Alpha'],
        'Beta_DP': reg3['Beta'][dp_col],
        'Beta_EP': reg3['Beta'][ep_col],
        'Beta_10Y': reg3['Beta'][yield_col],
        'R²': reg3['R²']
    })

if summary_data:
    summary_df = pd.DataFrame(summary_data)
    print(summary_df.to_string(index=False))


LAGGED REGRESSION: r^SPY_t = α + β'X_{t-1} + ε_t

Dependent variable: SPY excess returns
Predictors: SPX D/P, SPX E/P, T-Note 10YR

Data ranges:
  SPY excess returns: 1996-12-31 to 2025-10-31
  Signals: 1996-12-31 to 2025-10-31

1. Regression with DP (dividend-price ratio) only
Alpha: -0.082401 (t-stat: -7.3154)
Beta (SPX D/P): 3.846271 (t-stat: 6.2886)
R²: 0.103106
N observations: 346

2. Regression with EP (earnings-price ratio) only
Alpha: -0.041517 (t-stat: -3.6886)
Beta (SPX E/P): 0.523302 (t-stat: 2.5757)
R²: 0.018921
N observations: 346

3. Regression with DP, EP, and 10-year yield
Alpha: -0.013337 (t-stat: -0.8309)
Beta (SPX D/P): 1.926131 (t-stat: 2.0781)
Beta (SPX E/P): 0.070757 (t-stat: 0.2699)
Beta (T-Note 10YR): -1.083381 (t-stat: -5.4951)
R²: 0.183655
N observations: 346

SUMMARY TABLE
            Model     Alpha  Beta_DP       R²  Beta_EP  Beta_10Y
          DP only -0.082401 3.846271 0.103106      NaN       NaN
          EP only -0.041517      NaN 0.018921 0.523302     


2. **Trading strategy from forecasts.** For each of the three regressions:
   - Build the forecasted SPY return: $\hat r^{SPY}_{t+1}$ (forecast made using $X_t$ to predict $r^{SPY}_{t+1}$).
   - Set the scale (portfolio weight) to $w_t = 100 \,\hat r^{SPY}_{t+1}$.
   - Strategy return: $r^x_{t+1} = w_t\, r^{SPY}_{t+1}$.  
   For each strategy, compute:
   - mean, volatility, Sharpe
   - max drawdown
   - market **alpha**
   - market **beta**
   - market **information ratio**


In [41]:
# ============================================================================
# 2. Trading Strategy from Forecasts
# ============================================================================

# We need to rebuild the regression models to get the coefficients for forecasting
# Then use X_t to forecast r^{SPY}_{t+1}

print("="*80)
print("TRADING STRATEGY FROM FORECASTS")
print("="*80)

# Function to build forecasts and trading strategy
def build_trading_strategy(reg_result, signals_df, spy_returns, X_names, strategy_name):
    """
    Build trading strategy from regression forecasts.
    
    Steps:
    1. Build forecasted SPY return: r̂^{SPY}_{t+1} = α + β'X_t
    2. Set portfolio weight: w_t = 100 * r̂^{SPY}_{t+1}
    3. Strategy return: r^x_{t+1} = w_t * r^{SPY}_{t+1}
    """
    if reg_result is None:
        return None
    
    # Get regression coefficients
    alpha = reg_result['Alpha']
    beta_dict = reg_result['Beta']
    
    # Align data - we need X_t to forecast r^{SPY}_{t+1}
    # X_t is at time t, and we forecast r^{SPY}_{t+1} (next period return)
    common_idx = signals_df.index.intersection(spy_returns.index)
    signals_aligned = signals_df.loc[common_idx, X_names]
    spy_aligned = spy_returns.loc[common_idx]
    
    # Shift spy_returns forward by 1 period so r^{SPY}_{t+1} aligns with X_t
    spy_next = spy_aligned.shift(-1)  # r^{SPY}_{t+1}
    
    # Align again after shift
    common_idx_final = signals_aligned.index.intersection(spy_next.index)
    signals_final = signals_aligned.loc[common_idx_final]
    spy_next_final = spy_next.loc[common_idx_final]
    
    # Drop NaN
    valid_mask = ~(signals_final.isna().any(axis=1) | spy_next_final.isna())
    signals_clean = signals_final[valid_mask]
    spy_next_clean = spy_next_final[valid_mask]
    
    if len(signals_clean) == 0:
        return None
    
    # Build forecasts: r̂^{SPY}_{t+1} = α + β'X_t
    X_values = signals_clean.values
    forecasts = alpha + np.sum([beta_dict[name] * signals_clean[name].values 
                                for name in X_names], axis=0)
    
    # Portfolio weights: w_t = 100 * r̂^{SPY}_{t+1}
    weights = 100 * forecasts
    
    # Strategy returns: r^x_{t+1} = w_t * r^{SPY}_{t+1}
    strategy_returns = weights * spy_next_clean.values
    
    # Create Series with proper index
    strategy_returns_series = pd.Series(strategy_returns, index=signals_clean.index)
    
    return {
        'strategy_name': strategy_name,
        'forecasts': pd.Series(forecasts, index=signals_clean.index),
        'weights': pd.Series(weights, index=signals_clean.index),
        'strategy_returns': strategy_returns_series,
        'spy_returns': spy_next_clean
    }

# Function to calculate strategy statistics
def calculate_strategy_stats(strategy_dict, spy_market):
    """Calculate statistics for trading strategy."""
    if strategy_dict is None:
        return None
    
    strategy_ret = strategy_dict['strategy_returns']
    spy_ret = strategy_dict['spy_returns']
    
    # Mean, volatility, Sharpe (annualized)
    mean_monthly = strategy_ret.mean()
    vol_monthly = strategy_ret.std()
    sharpe_monthly = mean_monthly / vol_monthly if vol_monthly > 0 else np.nan
    
    mean_annual = mean_monthly * 12
    vol_annual = vol_monthly * np.sqrt(12)
    sharpe_annual = mean_annual / vol_annual if vol_annual > 0 else np.nan
    
    # Maximum drawdown (on total returns, need to convert to cumulative)
    cumulative = (1 + strategy_ret).cumprod()
    running_max = cumulative.expanding().max()
    drawdown = (cumulative - running_max) / running_max
    max_drawdown = drawdown.min()
    
    # Market alpha and beta (regress strategy returns on market returns)
    # Align indices
    common_idx = strategy_ret.index.intersection(spy_market.index)
    strategy_aligned = strategy_ret.loc[common_idx]
    market_aligned = spy_market.loc[common_idx]
    
    if len(strategy_aligned) > 0:
        X = market_aligned.values.reshape(-1, 1)
        y = strategy_aligned.values
        
        reg = LinearRegression()
        reg.fit(X, y)
        y_pred = reg.predict(X)
        
        # Alpha and beta
        alpha = reg.intercept_
        beta = reg.coef_[0]
        
        # Information ratio = alpha / tracking error
        residuals = y - y_pred
        tracking_error = np.std(residuals)
        information_ratio = alpha / tracking_error if tracking_error > 0 else np.nan
        
        # Annualize information ratio
        info_ratio_annual = information_ratio * np.sqrt(12) if not np.isnan(information_ratio) else np.nan
    else:
        alpha = np.nan
        beta = np.nan
        information_ratio = np.nan
        info_ratio_annual = np.nan
    
    return {
        'Mean (annualized)': mean_annual,
        'Volatility (annualized)': vol_annual,
        'Sharpe Ratio (annualized)': sharpe_annual,
        'Max Drawdown': max_drawdown,
        'Market Alpha': alpha,
        'Market Beta': beta,
        'Information Ratio (annualized)': info_ratio_annual,
        'N observations': len(strategy_ret)
    }

# Build strategies for all three regressions
print("\nBuilding trading strategies...")

# Strategy 1: DP only
strategy1 = build_trading_strategy(reg1, signals, spy_excess, [dp_col], 'DP only')
stats1 = calculate_strategy_stats(strategy1, spy_excess) if strategy1 else None

# Strategy 2: EP only
strategy2 = build_trading_strategy(reg2, signals, spy_excess, [ep_col], 'EP only')
stats2 = calculate_strategy_stats(strategy2, spy_excess) if strategy2 else None

# Strategy 3: DP, EP, 10Y Yield
strategy3 = build_trading_strategy(reg3, signals, spy_excess, [dp_col, ep_col, yield_col], 'DP, EP, 10Y Yield')
stats3 = calculate_strategy_stats(strategy3, spy_excess) if strategy3 else None

# Display results
print("\n" + "="*80)
print("STRATEGY 1: DP only")
print("="*80)
if stats1:
    for key, value in stats1.items():
        if isinstance(value, float):
            print(f"{key}: {value:.6f}")
        else:
            print(f"{key}: {value}")
else:
    print("Strategy calculation failed")

print("\n" + "="*80)
print("STRATEGY 2: EP only")
print("="*80)
if stats2:
    for key, value in stats2.items():
        if isinstance(value, float):
            print(f"{key}: {value:.6f}")
        else:
            print(f"{key}: {value}")
else:
    print("Strategy calculation failed")

print("\n" + "="*80)
print("STRATEGY 3: DP, EP, 10Y Yield")
print("="*80)
if stats3:
    for key, value in stats3.items():
        if isinstance(value, float):
            print(f"{key}: {value:.6f}")
        else:
            print(f"{key}: {value}")
else:
    print("Strategy calculation failed")

# Summary table
print("\n" + "="*80)
print("SUMMARY TABLE: Trading Strategy Statistics")
print("="*80)
summary_data = []
if stats1:
    summary_data.append({
        'Strategy': 'DP only',
        'Mean (annualized)': stats1['Mean (annualized)'],
        'Volatility (annualized)': stats1['Volatility (annualized)'],
        'Sharpe Ratio': stats1['Sharpe Ratio (annualized)'],
        'Max Drawdown': stats1['Max Drawdown'],
        'Market Alpha': stats1['Market Alpha'],
        'Market Beta': stats1['Market Beta'],
        'Info Ratio (annualized)': stats1['Information Ratio (annualized)']
    })
if stats2:
    summary_data.append({
        'Strategy': 'EP only',
        'Mean (annualized)': stats2['Mean (annualized)'],
        'Volatility (annualized)': stats2['Volatility (annualized)'],
        'Sharpe Ratio': stats2['Sharpe Ratio (annualized)'],
        'Max Drawdown': stats2['Max Drawdown'],
        'Market Alpha': stats2['Market Alpha'],
        'Market Beta': stats2['Market Beta'],
        'Info Ratio (annualized)': stats2['Information Ratio (annualized)']
    })
if stats3:
    summary_data.append({
        'Strategy': 'DP, EP, 10Y Yield',
        'Mean (annualized)': stats3['Mean (annualized)'],
        'Volatility (annualized)': stats3['Volatility (annualized)'],
        'Sharpe Ratio': stats3['Sharpe Ratio (annualized)'],
        'Max Drawdown': stats3['Max Drawdown'],
        'Market Alpha': stats3['Market Alpha'],
        'Market Beta': stats3['Market Beta'],
        'Info Ratio (annualized)': stats3['Information Ratio (annualized)']
    })

if summary_data:
    summary_df = pd.DataFrame(summary_data)
    print(summary_df.to_string(index=False))


TRADING STRATEGY FROM FORECASTS

Building trading strategies...

STRATEGY 1: DP only
Mean (annualized): 0.505219
Volatility (annualized): 0.415142
Sharpe Ratio (annualized): 1.216980
Max Drawdown: -0.809579
Market Alpha: 0.039233
Market Beta: -0.212704
Information Ratio (annualized): 1.140000
N observations: 346

STRATEGY 2: EP only
Mean (annualized): 0.266259
Volatility (annualized): 0.250071
Sharpe Ratio (annualized): 1.064733
Max Drawdown: -0.781260
Market Alpha: 0.019093
Market Beta: -0.229525
Information Ratio (annualized): 0.928796
N observations: 346

STRATEGY 3: DP, EP, 10Y Yield
Mean (annualized): 0.733855
Volatility (annualized): 0.474515
Sharpe Ratio (annualized): 1.546539
Max Drawdown: -0.494226
Market Alpha: 0.055334
Market Beta: -0.431638
Information Ratio (annualized): 1.418252
N observations: 346

SUMMARY TABLE: Trading Strategy Statistics
         Strategy  Mean (annualized)  Volatility (annualized)  Sharpe Ratio  Max Drawdown  Market Alpha  Market Beta  Info Ratio (an


3. **Risk characteristics.**
   - For both strategies, the market, and GMO, compute monthly **VaR** at $\pi = 0.05$ (use the historical quantile).
   - The case mentions stocks under‑performed short‑term bonds from 2000–2011. Does the dynamic portfolio above under‑perform the risk‑free rate over this time?
   - Based on the regression estimates, in how many periods do we estimate a **negative risk premium**?
   - Do you believe the dynamic strategy takes on **extra risk**?

In [42]:
# ============================================================================
# 3. Risk Characteristics
# ============================================================================

print("="*80)
print("RISK CHARACTERISTICS ANALYSIS")
print("="*80)

# ============================================================================
# 1. Compute monthly VaR at π = 0.05 (5th percentile) for strategies, market, and GMO
# ============================================================================

def calculate_var(returns, percentile=0.05):
    """Calculate Value at Risk (VaR) using historical quantile."""
    if len(returns) == 0:
        return np.nan
    return returns.quantile(percentile)

# Get market returns (SPY excess returns)
market_returns = spy_excess

# Get GMO returns (GMWAX excess returns)
gmo_returns = excess_returns['GMWAX'].dropna()

# Calculate VaR for each
print("\n" + "="*80)
print("1. Monthly VaR at π = 0.05 (5th percentile)")
print("="*80)

var_market = calculate_var(market_returns, 0.05)
var_gmo = calculate_var(gmo_returns, 0.05)

print(f"Market (SPY): {var_market:.6f} ({var_market*100:.2f}%)")
print(f"GMO (GMWAX): {var_gmo:.6f} ({var_gmo*100:.2f}%)")

# Strategy VaRs
if strategy1:
    var_strategy1 = calculate_var(strategy1['strategy_returns'], 0.05)
    print(f"Strategy 1 (DP only): {var_strategy1:.6f} ({var_strategy1*100:.2f}%)")
else:
    var_strategy1 = np.nan

if strategy2:
    var_strategy2 = calculate_var(strategy2['strategy_returns'], 0.05)
    print(f"Strategy 2 (EP only): {var_strategy2:.6f} ({var_strategy2*100:.2f}%)")
else:
    var_strategy2 = np.nan

if strategy3:
    var_strategy3 = calculate_var(strategy3['strategy_returns'], 0.05)
    print(f"Strategy 3 (DP, EP, 10Y Yield): {var_strategy3:.6f} ({var_strategy3*100:.2f}%)")
else:
    var_strategy3 = np.nan

# ============================================================================
# 2. Check if dynamic portfolio underperforms risk-free rate from 2000-2011
# ============================================================================

print("\n" + "="*80)
print("2. Dynamic Portfolio Performance vs Risk-Free Rate (2000-2011)")
print("="*80)

# Define period
start_2000 = pd.Timestamp('2000-01-01')
end_2011 = pd.Timestamp('2011-12-31')

# Get risk-free rate for this period
rf_period = risk_free_rate['TBill 3M'].loc[(risk_free_rate.index >= start_2000) & 
                                            (risk_free_rate.index <= end_2011)]

# Convert to monthly if annualized (check if values > 0.1)
if rf_period.max() > 0.1:
    rf_monthly = rf_period / 12
else:
    rf_monthly = rf_period

print(f"\nPeriod: {start_2000.date()} to {end_2011.date()}")
print(f"Risk-free rate (monthly, average): {rf_monthly.mean():.6f} ({rf_monthly.mean()*100:.2f}%)")

# Check each strategy
strategies_to_check = [
    (strategy1, 'Strategy 1 (DP only)'),
    (strategy2, 'Strategy 2 (EP only)'),
    (strategy3, 'Strategy 3 (DP, EP, 10Y Yield)')
]

for strategy, name in strategies_to_check:
    if strategy:
        strategy_ret = strategy['strategy_returns']
        strategy_period = strategy_ret.loc[(strategy_ret.index >= start_2000) & 
                                          (strategy_ret.index <= end_2011)]
        
        if len(strategy_period) > 0:
            # Align with risk-free rate
            common_idx = strategy_period.index.intersection(rf_monthly.index)
            strategy_aligned = strategy_period.loc[common_idx]
            rf_aligned = rf_monthly.loc[common_idx]
            
            # Calculate excess return over risk-free rate
            excess_over_rf = strategy_aligned - rf_aligned
            mean_excess = excess_over_rf.mean()
            total_excess = (1 + excess_over_rf).prod() - 1  # Cumulative excess return
            
            print(f"\n{name}:")
            print(f"  Mean monthly return: {strategy_aligned.mean():.6f} ({strategy_aligned.mean()*100:.2f}%)")
            print(f"  Mean excess over RF: {mean_excess:.6f} ({mean_excess*100:.2f}%)")
            print(f"  Cumulative excess return: {total_excess:.6f} ({total_excess*100:.2f}%)")
            
            if mean_excess < 0:
                print(f"  ✓ Underperforms risk-free rate (negative excess return)")
            else:
                print(f"  ✗ Outperforms risk-free rate (positive excess return)")

# ============================================================================
# 3. Count periods with negative risk premium based on regression estimates
# ============================================================================

print("\n" + "="*80)
print("3. Periods with Negative Risk Premium (based on regression forecasts)")
print("="*80)

def count_negative_premiums(reg_result, signals_df, X_names):
    """Count how many periods have negative forecasted risk premium."""
    if reg_result is None:
        return None
    
    alpha = reg_result['Alpha']
    beta_dict = reg_result['Beta']
    
    # Align data
    common_idx = signals_df.index.intersection(spy_excess.index)
    signals_aligned = signals_df.loc[common_idx, X_names]
    
    # Drop NaN
    valid_mask = ~signals_aligned.isna().any(axis=1)
    signals_clean = signals_aligned[valid_mask]
    
    if len(signals_clean) == 0:
        return None
    
    # Build forecasts: r̂^{SPY}_{t+1} = α + β'X_t
    forecasts = alpha + np.sum([beta_dict[name] * signals_clean[name].values 
                                for name in X_names], axis=0)
    
    # Count negative forecasts (negative risk premium)
    negative_count = np.sum(forecasts < 0)
    total_count = len(forecasts)
    negative_pct = (negative_count / total_count) * 100 if total_count > 0 else 0
    
    return {
        'negative_count': negative_count,
        'total_count': total_count,
        'negative_pct': negative_pct,
        'forecasts': pd.Series(forecasts, index=signals_clean.index)
    }

# Count for each regression
neg1 = count_negative_premiums(reg1, signals, [dp_col])
neg2 = count_negative_premiums(reg2, signals, [ep_col])
neg3 = count_negative_premiums(reg3, signals, [dp_col, ep_col, yield_col])

if neg1:
    print(f"\nStrategy 1 (DP only):")
    print(f"  Periods with negative risk premium: {neg1['negative_count']} out of {neg1['total_count']} ({neg1['negative_pct']:.2f}%)")

if neg2:
    print(f"\nStrategy 2 (EP only):")
    print(f"  Periods with negative risk premium: {neg2['negative_count']} out of {neg2['total_count']} ({neg2['negative_pct']:.2f}%)")

if neg3:
    print(f"\nStrategy 3 (DP, EP, 10Y Yield):")
    print(f"  Periods with negative risk premium: {neg3['negative_count']} out of {neg3['total_count']} ({neg3['negative_pct']:.2f}%)")

# ============================================================================
# 4. Assess if dynamic strategy takes on extra risk
# ============================================================================

print("\n" + "="*80)
print("4. Does the Dynamic Strategy Take on Extra Risk?")
print("="*80)

print("\nRisk Comparison:")
print("-" * 80)

# Compare volatilities
if stats1 and stats2 and stats3:
    print(f"\nVolatility (annualized):")
    print(f"  Market (SPY): {market_returns.std() * np.sqrt(12):.6f} ({market_returns.std() * np.sqrt(12)*100:.2f}%)")
    print(f"  Strategy 1 (DP only): {stats1['Volatility (annualized)']:.6f} ({stats1['Volatility (annualized)']*100:.2f}%)")
    print(f"  Strategy 2 (EP only): {stats2['Volatility (annualized)']:.6f} ({stats2['Volatility (annualized)']*100:.2f}%)")
    print(f"  Strategy 3 (DP, EP, 10Y Yield): {stats3['Volatility (annualized)']:.6f} ({stats3['Volatility (annualized)']*100:.2f}%)")
    
    # Compare VaRs
    print(f"\nVaR (5th percentile):")
    print(f"  Market (SPY): {var_market:.6f} ({var_market*100:.2f}%)")
    print(f"  Strategy 1 (DP only): {var_strategy1:.6f} ({var_strategy1*100:.2f}%)")
    print(f"  Strategy 2 (EP only): {var_strategy2:.6f} ({var_strategy2*100:.2f}%)")
    print(f"  Strategy 3 (DP, EP, 10Y Yield): {var_strategy3:.6f} ({var_strategy3*100:.2f}%)")
    
    # Compare max drawdowns
    market_cumulative = (1 + market_returns).cumprod()
    market_running_max = market_cumulative.expanding().max()
    market_drawdown = (market_cumulative - market_running_max) / market_running_max
    market_max_dd = market_drawdown.min()
    
    print(f"\nMaximum Drawdown:")
    print(f"  Market (SPY): {market_max_dd:.6f} ({market_max_dd*100:.2f}%)")
    print(f"  Strategy 1 (DP only): {stats1['Max Drawdown']:.6f} ({stats1['Max Drawdown']*100:.2f}%)")
    print(f"  Strategy 2 (EP only): {stats2['Max Drawdown']:.6f} ({stats2['Max Drawdown']*100:.2f}%)")
    print(f"  Strategy 3 (DP, EP, 10Y Yield): {stats3['Max Drawdown']:.6f} ({stats3['Max Drawdown']*100:.2f}%)")
    
    # Compare betas
    print(f"\nMarket Beta:")
    print(f"  Strategy 1 (DP only): {stats1['Market Beta']:.4f}")
    print(f"  Strategy 2 (EP only): {stats2['Market Beta']:.4f}")
    print(f"  Strategy 3 (DP, EP, 10Y Yield): {stats3['Market Beta']:.4f}")
    print(f"  (Market beta = 1.0 by definition)")

print("\n" + "="*80)
print("ASSESSMENT:")
print("="*80)
print("\nThe dynamic strategy takes on EXTRA RISK if:")
print("  - Volatility is higher than the market")
print("  - VaR is more negative (worse) than the market")
print("  - Maximum drawdown is larger (more negative) than the market")
print("  - Market beta is greater than 1.0")
print("\nCompare the metrics above to assess whether each strategy takes on extra risk.")


RISK CHARACTERISTICS ANALYSIS

1. Monthly VaR at π = 0.05 (5th percentile)
Market (SPY): -0.098914 (-9.89%)
GMO (GMWAX): -0.077006 (-7.70%)
Strategy 1 (DP only): -0.078998 (-7.90%)
Strategy 2 (EP only): -0.074008 (-7.40%)
Strategy 3 (DP, EP, 10Y Yield): -0.065591 (-6.56%)

2. Dynamic Portfolio Performance vs Risk-Free Rate (2000-2011)

Period: 2000-01-01 to 2011-12-31
Risk-free rate (monthly, average): 0.022875 (2.29%)

Strategy 1 (DP only):
  Mean monthly return: 0.053109 (5.31%)
  Mean excess over RF: 0.030233 (3.02%)
  Cumulative excess return: 19.143938 (1914.39%)
  ✗ Outperforms risk-free rate (positive excess return)

Strategy 2 (EP only):
  Mean monthly return: 0.031962 (3.20%)
  Mean excess over RF: 0.009086 (0.91%)
  Cumulative excess return: 1.794594 (179.46%)
  ✗ Outperforms risk-free rate (positive excess return)

Strategy 3 (DP, EP, 10Y Yield):
  Mean monthly return: 0.078094 (7.81%)
  Mean excess over RF: 0.055218 (5.52%)
  Cumulative excess return: 643.748892 (64374.89%)

## 4 Out‑of‑Sample Forecasting

_This section utilizes data in `gmo_data.xlsx`._ Focus on using **both** $DP$ and $EP$ as signals in (1). Compute **out‑of‑sample** ($OOS$) statistics:

**Procedure (rolling OOS):**
- Start at $t=60$.
- Estimate (1) using data **through** time $t$.
- Using the estimated parameters and $x_t$, compute the forecast for $t+1$:
  
  $$
  \hat r^{SPY}_{t+1} \;=\; \hat \alpha^{SPY,X}_t \;+\; \big(\hat \beta^{SPY,X}_t\big)^\prime x_t
  $$

- Forecast error: $e^{forecast}_{t+1} = r^{SPY}_{t+1} - \hat r^{SPY}_{t+1}$.
- Move to $t=61$ and iterate.

Also compute the **null** forecast and errors:

$$
\bar r^{SPY}_{t+1} = \frac{1}{t}\sum_{i=1}^t r^{SPY}_i, \qquad
e^{null}_{t+1} = r^{SPY}_{t+1} - \bar r^{SPY}_{t+1}.
$$

1. **Report the out‑of‑sample $R^2$**

$$
R^2_{OOS} \;\equiv\; 1 - \frac{\sum_{i=61}^T \big(e^{forecast}_i\big)^2}{\sum_{i=61}^T \big(e^{null}_i\big)^2}
$$

Did this forecasting strategy produce a positive $R^2_{OOS}$?


In [43]:
# ============================================================================
# 4. Out-of-Sample Forecasting
# Focus on using both DP and EP as signals
# ============================================================================

print("="*80)
print("OUT-OF-SAMPLE FORECASTING")
print("="*80)
print("\nUsing both DP and EP as signals for forecasting")

# Align data
common_idx = signals.index.intersection(spy_excess.index)
signals_aligned = signals.loc[common_idx, [dp_col, ep_col]]
spy_aligned = spy_excess.loc[common_idx]

# Sort by date to ensure proper ordering
signals_aligned = signals_aligned.sort_index()
spy_aligned = spy_aligned.sort_index()

# Remove any NaN rows
valid_mask = ~(signals_aligned.isna().any(axis=1) | spy_aligned.isna())
signals_clean = signals_aligned[valid_mask]
spy_clean = spy_aligned[valid_mask]

print(f"\nData range: {spy_clean.index.min().date()} to {spy_clean.index.max().date()}")
print(f"Total observations: {len(spy_clean)}")
print(f"Starting OOS at t=60 (observation {spy_clean.index[60]})")

# Initialize storage for forecasts and errors
forecast_errors = []
null_errors = []
forecast_values = []
null_forecast_values = []
actual_returns = []

# Rolling out-of-sample procedure
# Start at t=60 (0-indexed, so t=60 means we use observations 0-60 to forecast 61)
start_idx = 60
T = len(spy_clean)

print(f"\nRunning rolling OOS procedure from t={start_idx} to t={T-2}...")

for t in range(start_idx, T - 1):  # T-1 because we need t+1 to exist
    # Data through time t (for estimation)
    spy_train = spy_clean.iloc[:t+1]  # Observations 0 to t (inclusive)
    signals_train = signals_clean.iloc[:t+1]
    
    # X_t (predictors at time t) for forecasting
    x_t = signals_clean.iloc[t:t+1]  # Signals at time t
    
    # r^{SPY}_{t+1} (actual return at time t+1)
    r_t_plus_1 = spy_clean.iloc[t+1]
    
    # Drop NaN from training data
    train_mask = ~(signals_train.isna().any(axis=1) | spy_train.isna())
    signals_train_clean = signals_train[train_mask]
    spy_train_clean = spy_train[train_mask]
    
    if len(signals_train_clean) < 2:  # Need at least 2 observations
        continue
    
    # Estimate regression using data through time t
    # r^{SPY}_i = α + β'X_{i-1} + ε_i for i = 1 to t
    # We need to lag the signals
    signals_train_lagged = signals_train_clean.shift(1).iloc[1:]  # X_{i-1}
    spy_train_aligned = spy_train_clean.iloc[1:]  # r^{SPY}_i
    
    # Align after lag
    common_train_idx = signals_train_lagged.index.intersection(spy_train_aligned.index)
    signals_train_final = signals_train_lagged.loc[common_train_idx]
    spy_train_final = spy_train_aligned.loc[common_train_idx]
    
    if len(signals_train_final) < 2:
        continue
    
    # Fit regression
    X_train = signals_train_final.values
    y_train = spy_train_final.values
    
    reg = LinearRegression()
    reg.fit(X_train, y_train)
    
    # Forecast r^{SPY}_{t+1} using x_t
    x_t_values = x_t.values
    forecast = reg.intercept_ + np.dot(reg.coef_, x_t_values[0])
    
    # Forecast error
    forecast_error = r_t_plus_1 - forecast
    
    # Null forecast: mean of returns through time t
    null_forecast = spy_train_clean.mean()
    null_error = r_t_plus_1 - null_forecast
    
    # Store results
    forecast_errors.append(forecast_error)
    null_errors.append(null_error)
    forecast_values.append(forecast)
    null_forecast_values.append(null_forecast)
    actual_returns.append(r_t_plus_1)

# Convert to arrays
forecast_errors = np.array(forecast_errors)
null_errors = np.array(null_errors)

# Calculate out-of-sample R²
sum_squared_forecast_errors = np.sum(forecast_errors ** 2)
sum_squared_null_errors = np.sum(null_errors ** 2)

if sum_squared_null_errors > 0:
    r2_oos = 1 - (sum_squared_forecast_errors / sum_squared_null_errors)
else:
    r2_oos = np.nan

# Display results
print("\n" + "="*80)
print("OUT-OF-SAMPLE RESULTS")
print("="*80)
print(f"\nNumber of OOS forecasts: {len(forecast_errors)}")
print(f"Sum of squared forecast errors: {sum_squared_forecast_errors:.6f}")
print(f"Sum of squared null errors: {sum_squared_null_errors:.6f}")
print(f"\nOut-of-Sample R²: {r2_oos:.6f}")

if r2_oos > 0:
    print(f"\n✓ YES - The forecasting strategy produced a POSITIVE R²_OOS ({r2_oos:.6f})")
    print("  This means the model forecasts are better than the null (mean) forecast.")
elif r2_oos < 0:
    print(f"\n✗ NO - The forecasting strategy produced a NEGATIVE R²_OOS ({r2_oos:.6f})")
    print("  This means the model forecasts are worse than the null (mean) forecast.")
else:
    print(f"\nThe forecasting strategy produced R²_OOS = 0")
    print("  This means the model forecasts perform the same as the null (mean) forecast.")

# Additional statistics
print("\n" + "="*80)
print("ADDITIONAL STATISTICS")
print("="*80)
print(f"Mean forecast error: {np.mean(forecast_errors):.6f}")
print(f"RMSE (forecast): {np.sqrt(np.mean(forecast_errors**2)):.6f}")
print(f"Mean null error: {np.mean(null_errors):.6f}")
print(f"RMSE (null): {np.sqrt(np.mean(null_errors**2)):.6f}")

if np.sqrt(np.mean(forecast_errors**2)) < np.sqrt(np.mean(null_errors**2)):
    improvement = ((np.sqrt(np.mean(null_errors**2)) - np.sqrt(np.mean(forecast_errors**2))) / 
                   np.sqrt(np.mean(null_errors**2))) * 100
    print(f"\nForecast RMSE is {improvement:.2f}% lower than null forecast RMSE")
else:
    deterioration = ((np.sqrt(np.mean(forecast_errors**2)) - np.sqrt(np.mean(null_errors**2))) / 
                     np.sqrt(np.mean(null_errors**2))) * 100
    print(f"\nForecast RMSE is {deterioration:.2f}% higher than null forecast RMSE")


OUT-OF-SAMPLE FORECASTING

Using both DP and EP as signals for forecasting

Data range: 1996-12-31 to 2025-10-31
Total observations: 347
Starting OOS at t=60 (observation 2001-12-31 00:00:00)

Running rolling OOS procedure from t=60 to t=345...

OUT-OF-SAMPLE RESULTS

Number of OOS forecasts: 286
Sum of squared forecast errors: 0.605409
Sum of squared null errors: 0.663985

Out-of-Sample R²: 0.088220

✓ YES - The forecasting strategy produced a POSITIVE R²_OOS (0.088220)
  This means the model forecasts are better than the null (mean) forecast.

ADDITIONAL STATISTICS
Mean forecast error: 0.004922
RMSE (forecast): 0.046009
Mean null error: 0.013239
RMSE (null): 0.048183

Forecast RMSE is 4.51% lower than null forecast RMSE


2. **Redo 3.2 with OOS forecasts.** How does the OOS strategy compare to the in‑sample version of 3.2?

In [44]:
# ============================================================================
# 2. Redo 3.2 with OOS Forecasts
# Build trading strategy using out-of-sample forecasts and compare to in-sample
# ============================================================================

print("="*80)
print("TRADING STRATEGY FROM OUT-OF-SAMPLE FORECASTS")
print("="*80)

# We need to rebuild the OOS procedure to get forecasts and build the strategy
# The forecasts from the previous cell should be available, but let's rebuild to ensure we have everything

# Rebuild OOS forecasts and strategy returns
oos_forecasts_list = []
oos_weights_list = []
oos_strategy_returns_list = []
oos_actual_returns_list = []
oos_dates = []

# Align data (same as before)
common_idx = signals.index.intersection(spy_excess.index)
signals_aligned = signals.loc[common_idx, [dp_col, ep_col]]
spy_aligned = spy_excess.loc[common_idx]

signals_aligned = signals_aligned.sort_index()
spy_aligned = spy_aligned.sort_index()

valid_mask = ~(signals_aligned.isna().any(axis=1) | spy_aligned.isna())
signals_clean = signals_aligned[valid_mask]
spy_clean = spy_aligned[valid_mask]

start_idx = 60
T = len(spy_clean)

print(f"\nBuilding OOS trading strategy from t={start_idx} to t={T-2}...")

for t in range(start_idx, T - 1):
    # Data through time t (for estimation)
    spy_train = spy_clean.iloc[:t+1]
    signals_train = signals_clean.iloc[:t+1]
    
    # X_t (predictors at time t) for forecasting
    x_t = signals_clean.iloc[t:t+1]
    
    # r^{SPY}_{t+1} (actual return at time t+1)
    r_t_plus_1 = spy_clean.iloc[t+1]
    date_t_plus_1 = spy_clean.index[t+1]
    
    # Drop NaN from training data
    train_mask = ~(signals_train.isna().any(axis=1) | spy_train.isna())
    signals_train_clean = signals_train[train_mask]
    spy_train_clean = spy_train[train_mask]
    
    if len(signals_train_clean) < 2:
        continue
    
    # Estimate regression using data through time t (with lagging)
    signals_train_lagged = signals_train_clean.shift(1).iloc[1:]
    spy_train_aligned = spy_train_clean.iloc[1:]
    
    common_train_idx = signals_train_lagged.index.intersection(spy_train_aligned.index)
    signals_train_final = signals_train_lagged.loc[common_train_idx]
    spy_train_final = spy_train_aligned.loc[common_train_idx]
    
    if len(signals_train_final) < 2:
        continue
    
    # Fit regression
    X_train = signals_train_final.values
    y_train = spy_train_final.values
    
    reg = LinearRegression()
    reg.fit(X_train, y_train)
    
    # Forecast r^{SPY}_{t+1} using x_t
    x_t_values = x_t.values
    forecast = reg.intercept_ + np.dot(reg.coef_, x_t_values[0])
    
    # Portfolio weight: w_t = 100 * r̂^{SPY}_{t+1}
    weight = 100 * forecast
    
    # Strategy return: r^x_{t+1} = w_t * r^{SPY}_{t+1}
    strategy_return = weight * r_t_plus_1
    
    # Store results
    oos_forecasts_list.append(forecast)
    oos_weights_list.append(weight)
    oos_strategy_returns_list.append(strategy_return)
    oos_actual_returns_list.append(r_t_plus_1)
    oos_dates.append(date_t_plus_1)

# Create Series for OOS strategy
oos_strategy_returns = pd.Series(oos_strategy_returns_list, index=oos_dates)
oos_actual_returns_series = pd.Series(oos_actual_returns_list, index=oos_dates)

# Calculate OOS strategy statistics
def calculate_strategy_stats_oos(strategy_returns, market_returns):
    """Calculate statistics for OOS trading strategy."""
    if len(strategy_returns) == 0:
        return None
    
    # Mean, volatility, Sharpe (annualized)
    mean_monthly = strategy_returns.mean()
    vol_monthly = strategy_returns.std()
    sharpe_monthly = mean_monthly / vol_monthly if vol_monthly > 0 else np.nan
    
    mean_annual = mean_monthly * 12
    vol_annual = vol_monthly * np.sqrt(12)
    sharpe_annual = mean_annual / vol_annual if vol_annual > 0 else np.nan
    
    # Maximum drawdown
    cumulative = (1 + strategy_returns).cumprod()
    running_max = cumulative.expanding().max()
    drawdown = (cumulative - running_max) / running_max
    max_drawdown = drawdown.min()
    
    # Market alpha and beta
    # Align indices
    common_idx = strategy_returns.index.intersection(market_returns.index)
    strategy_aligned = strategy_returns.loc[common_idx]
    market_aligned = market_returns.loc[common_idx]
    
    if len(strategy_aligned) > 0:
        X = market_aligned.values.reshape(-1, 1)
        y = strategy_aligned.values
        
        reg = LinearRegression()
        reg.fit(X, y)
        y_pred = reg.predict(X)
        
        alpha = reg.intercept_
        beta = reg.coef_[0]
        
        # Information ratio = alpha / tracking error
        residuals = y - y_pred
        tracking_error = np.std(residuals)
        information_ratio = alpha / tracking_error if tracking_error > 0 else np.nan
        info_ratio_annual = information_ratio * np.sqrt(12) if not np.isnan(information_ratio) else np.nan
    else:
        alpha = np.nan
        beta = np.nan
        info_ratio_annual = np.nan
    
    return {
        'Mean (annualized)': mean_annual,
        'Volatility (annualized)': vol_annual,
        'Sharpe Ratio (annualized)': sharpe_annual,
        'Max Drawdown': max_drawdown,
        'Market Alpha': alpha,
        'Market Beta': beta,
        'Information Ratio (annualized)': info_ratio_annual,
        'N observations': len(strategy_returns)
    }

# Calculate OOS strategy statistics
oos_stats = calculate_strategy_stats_oos(oos_strategy_returns, spy_excess)

# Get in-sample strategy statistics (Strategy 3 from section 3.2, which used DP and EP)
# Note: strategy3 should be available from the earlier code
in_sample_stats = stats3 if 'stats3' in globals() and stats3 else None

# Display results
print("\n" + "="*80)
print("OUT-OF-SAMPLE STRATEGY STATISTICS")
print("="*80)
if oos_stats:
    for key, value in oos_stats.items():
        if isinstance(value, float):
            print(f"{key}: {value:.6f}")
        else:
            print(f"{key}: {value}")

print("\n" + "="*80)
print("IN-SAMPLE STRATEGY STATISTICS (from section 3.2)")
print("="*80)
if in_sample_stats:
    for key, value in in_sample_stats.items():
        if isinstance(value, float):
            print(f"{key}: {value:.6f}")
        else:
            print(f"{key}: {value}")
else:
    print("In-sample statistics not available. Please run section 3.2 first.")

# Comparison
print("\n" + "="*80)
print("COMPARISON: OOS vs IN-SAMPLE STRATEGY")
print("="*80)

if oos_stats and in_sample_stats:
    print("\nMean Return (annualized):")
    print(f"  OOS Strategy: {oos_stats['Mean (annualized)']:.6f} ({oos_stats['Mean (annualized)']*100:.2f}%)")
    print(f"  In-Sample Strategy: {in_sample_stats['Mean (annualized)']:.6f} ({in_sample_stats['Mean (annualized)']*100:.2f}%)")
    mean_diff = oos_stats['Mean (annualized)'] - in_sample_stats['Mean (annualized)']
    print(f"  Difference: {mean_diff:+.6f} ({mean_diff*100:+.2f}%)")
    
    print("\nVolatility (annualized):")
    print(f"  OOS Strategy: {oos_stats['Volatility (annualized)']:.6f} ({oos_stats['Volatility (annualized)']*100:.2f}%)")
    print(f"  In-Sample Strategy: {in_sample_stats['Volatility (annualized)']:.6f} ({in_sample_stats['Volatility (annualized)']*100:.2f}%)")
    vol_diff = oos_stats['Volatility (annualized)'] - in_sample_stats['Volatility (annualized)']
    print(f"  Difference: {vol_diff:+.6f} ({vol_diff*100:+.2f}%)")
    
    print("\nSharpe Ratio (annualized):")
    print(f"  OOS Strategy: {oos_stats['Sharpe Ratio (annualized)']:.6f}")
    print(f"  In-Sample Strategy: {in_sample_stats['Sharpe Ratio (annualized)']:.6f}")
    sharpe_diff = oos_stats['Sharpe Ratio (annualized)'] - in_sample_stats['Sharpe Ratio (annualized)']
    print(f"  Difference: {sharpe_diff:+.6f}")
    
    print("\nMaximum Drawdown:")
    print(f"  OOS Strategy: {oos_stats['Max Drawdown']:.6f} ({oos_stats['Max Drawdown']*100:.2f}%)")
    print(f"  In-Sample Strategy: {in_sample_stats['Max Drawdown']:.6f} ({in_sample_stats['Max Drawdown']*100:.2f}%)")
    dd_diff = oos_stats['Max Drawdown'] - in_sample_stats['Max Drawdown']
    print(f"  Difference: {dd_diff:+.6f} ({dd_diff*100:+.2f}%)")
    
    print("\nMarket Alpha:")
    print(f"  OOS Strategy: {oos_stats['Market Alpha']:.6f}")
    print(f"  In-Sample Strategy: {in_sample_stats['Market Alpha']:.6f}")
    alpha_diff = oos_stats['Market Alpha'] - in_sample_stats['Market Alpha']
    print(f"  Difference: {alpha_diff:+.6f}")
    
    print("\nMarket Beta:")
    print(f"  OOS Strategy: {oos_stats['Market Beta']:.6f}")
    print(f"  In-Sample Strategy: {in_sample_stats['Market Beta']:.6f}")
    beta_diff = oos_stats['Market Beta'] - in_sample_stats['Market Beta']
    print(f"  Difference: {beta_diff:+.6f}")
    
    print("\nInformation Ratio (annualized):")
    print(f"  OOS Strategy: {oos_stats['Information Ratio (annualized)']:.6f}")
    print(f"  In-Sample Strategy: {in_sample_stats['Information Ratio (annualized)']:.6f}")
    ir_diff = oos_stats['Information Ratio (annualized)'] - in_sample_stats['Information Ratio (annualized)']
    print(f"  Difference: {ir_diff:+.6f}")
    

TRADING STRATEGY FROM OUT-OF-SAMPLE FORECASTS

Building OOS trading strategy from t=60 to t=345...

OUT-OF-SAMPLE STRATEGY STATISTICS
Mean (annualized): 0.212668
Volatility (annualized): 0.259100
Sharpe Ratio (annualized): 0.820797
Max Drawdown: -0.747516
Market Alpha: 0.007746
Market Beta: -1.250617
Information Ratio (annualized): 0.567514
N observations: 286

IN-SAMPLE STRATEGY STATISTICS (from section 3.2)
Mean (annualized): 0.733855
Volatility (annualized): 0.474515
Sharpe Ratio (annualized): 1.546539
Max Drawdown: -0.494226
Market Alpha: 0.055334
Market Beta: -0.431638
Information Ratio (annualized): 1.418252
N observations: 346

COMPARISON: OOS vs IN-SAMPLE STRATEGY

Mean Return (annualized):
  OOS Strategy: 0.212668 (21.27%)
  In-Sample Strategy: 0.733855 (73.39%)
  Difference: -0.521187 (-52.12%)

Volatility (annualized):
  OOS Strategy: 0.259100 (25.91%)
  In-Sample Strategy: 0.474515 (47.45%)
  Difference: -0.215415 (-21.54%)

Sharpe Ratio (annualized):
  OOS Strategy: 0.8207

How does the OOS strategy compare to the in-sample version?

Key observations:
  - OOS strategy has LOWER mean return than in-sample
  - OOS strategy has WORSE risk-adjusted returns (lower Sharpe)
  - OOS strategy has LOWER volatility than in-sample

Note: OOS strategy is more realistic as it uses only information available at each point in time.
In-sample strategy may be overfitted to the full dataset.

3. **Redo 3.3 with OOS forecasts.** Is the point‑in‑time version of the strategy **riskier**?

In [39]:
# ============================================================================
# 3. Redo 3.3 with OOS Forecasts - Risk Characteristics
# Is the point-in-time (OOS) version of the strategy riskier?
# ============================================================================

print("="*80)
print("RISK CHARACTERISTICS: OOS STRATEGY vs IN-SAMPLE STRATEGY")
print("="*80)

# ============================================================================
# 1. Compute monthly VaR at π = 0.05 for OOS strategy
# ============================================================================

def calculate_var(returns, percentile=0.05):
    """Calculate Value at Risk (VaR) using historical quantile."""
    if len(returns) == 0:
        return np.nan
    return returns.quantile(percentile)

print("\n" + "="*80)
print("1. Monthly VaR at π = 0.05 (5th percentile)")
print("="*80)

# OOS strategy VaR
if 'oos_strategy_returns' in globals() and len(oos_strategy_returns) > 0:
    var_oos = calculate_var(oos_strategy_returns, 0.05)
    print(f"OOS Strategy: {var_oos:.6f} ({var_oos*100:.2f}%)")
else:
    var_oos = np.nan
    print("OOS Strategy: Not available")

# In-sample strategy VaR (from section 3.3)
if 'strategy3' in globals() and strategy3:
    var_in_sample = calculate_var(strategy3['strategy_returns'], 0.05)
    print(f"In-Sample Strategy: {var_in_sample:.6f} ({var_in_sample*100:.2f}%)")
else:
    var_in_sample = np.nan
    print("In-Sample Strategy: Not available")

# Market and GMO VaR (for reference)
market_returns = spy_excess
gmo_returns = excess_returns['GMWAX'].dropna()
var_market = calculate_var(market_returns, 0.05)
var_gmo = calculate_var(gmo_returns, 0.05)
print(f"Market (SPY): {var_market:.6f} ({var_market*100:.2f}%)")
print(f"GMO (GMWAX): {var_gmo:.6f} ({var_gmo*100:.2f}%)")

# ============================================================================
# 2. Check if OOS strategy underperforms risk-free rate from 2000-2011
# ============================================================================

print("\n" + "="*80)
print("2. OOS Strategy Performance vs Risk-Free Rate (2000-2011)")
print("="*80)

start_2000 = pd.Timestamp('2000-01-01')
end_2011 = pd.Timestamp('2011-12-31')

# Get risk-free rate for this period
rf_period = risk_free_rate['TBill 3M'].loc[(risk_free_rate.index >= start_2000) & 
                                            (risk_free_rate.index <= end_2011)]

# Convert to monthly if annualized
if rf_period.max() > 0.1:
    rf_monthly = rf_period / 12
else:
    rf_monthly = rf_period

print(f"\nPeriod: {start_2000.date()} to {end_2011.date()}")
print(f"Risk-free rate (monthly, average): {rf_monthly.mean():.6f} ({rf_monthly.mean()*100:.2f}%)")

# OOS strategy performance
if 'oos_strategy_returns' in globals() and len(oos_strategy_returns) > 0:
    oos_period = oos_strategy_returns.loc[(oos_strategy_returns.index >= start_2000) & 
                                          (oos_strategy_returns.index <= end_2011)]
    
    if len(oos_period) > 0:
        common_idx = oos_period.index.intersection(rf_monthly.index)
        oos_aligned = oos_period.loc[common_idx]
        rf_aligned = rf_monthly.loc[common_idx]
        
        excess_over_rf_oos = oos_aligned - rf_aligned
        mean_excess_oos = excess_over_rf_oos.mean()
        total_excess_oos = (1 + excess_over_rf_oos).prod() - 1
        
        print(f"\nOOS Strategy:")
        print(f"  Mean monthly return: {oos_aligned.mean():.6f} ({oos_aligned.mean()*100:.2f}%)")
        print(f"  Mean excess over RF: {mean_excess_oos:.6f} ({mean_excess_oos*100:.2f}%)")
        print(f"  Cumulative excess return: {total_excess_oos:.6f} ({total_excess_oos*100:.2f}%)")
        
        if mean_excess_oos < 0:
            print(f"  ✓ Underperforms risk-free rate")
        else:
            print(f"  ✗ Outperforms risk-free rate")

# In-sample strategy performance (for comparison)
if 'strategy3' in globals() and strategy3:
    in_sample_period = strategy3['strategy_returns'].loc[(strategy3['strategy_returns'].index >= start_2000) & 
                                                         (strategy3['strategy_returns'].index <= end_2011)]
    
    if len(in_sample_period) > 0:
        common_idx = in_sample_period.index.intersection(rf_monthly.index)
        in_sample_aligned = in_sample_period.loc[common_idx]
        rf_aligned = rf_monthly.loc[common_idx]
        
        excess_over_rf_in = in_sample_aligned - rf_aligned
        mean_excess_in = excess_over_rf_in.mean()
        total_excess_in = (1 + excess_over_rf_in).prod() - 1
        
        print(f"\nIn-Sample Strategy:")
        print(f"  Mean monthly return: {in_sample_aligned.mean():.6f} ({in_sample_aligned.mean()*100:.2f}%)")
        print(f"  Mean excess over RF: {mean_excess_in:.6f} ({mean_excess_in*100:.2f}%)")
        print(f"  Cumulative excess return: {total_excess_in:.6f} ({total_excess_in*100:.2f}%)")
        
        if mean_excess_in < 0:
            print(f"  ✓ Underperforms risk-free rate")
        else:
            print(f"  ✗ Outperforms risk-free rate")

# ============================================================================
# 3. Count periods with negative risk premium (based on OOS forecasts)
# ============================================================================

print("\n" + "="*80)
print("3. Periods with Negative Risk Premium (OOS forecasts)")
print("="*80)

# Count negative forecasts from OOS procedure
if 'oos_forecasts_list' in globals() and len(oos_forecasts_list) > 0:
    oos_forecasts_array = np.array(oos_forecasts_list)
    negative_count_oos = np.sum(oos_forecasts_array < 0)
    total_count_oos = len(oos_forecasts_array)
    negative_pct_oos = (negative_count_oos / total_count_oos) * 100 if total_count_oos > 0 else 0
    
    print(f"\nOOS Strategy:")
    print(f"  Periods with negative risk premium: {negative_count_oos} out of {total_count_oos} ({negative_pct_oos:.2f}%)")
else:
    print("\nOOS forecasts not available")

# In-sample comparison (from section 3.3)
if 'neg3' in globals() and neg3:
    print(f"\nIn-Sample Strategy (from section 3.3):")
    print(f"  Periods with negative risk premium: {neg3['negative_count']} out of {neg3['total_count']} ({neg3['negative_pct']:.2f}%)")

# ============================================================================
# 4. Assess if OOS strategy takes on extra risk (compared to in-sample and market)
# ============================================================================

print("\n" + "="*80)
print("4. Is the Point-in-Time (OOS) Strategy Riskier?")
print("="*80)

print("\nRisk Comparison:")
print("-" * 80)

# Get statistics
oos_stats_available = 'oos_stats' in globals() and oos_stats
in_sample_stats_available = 'stats3' in globals() and stats3

if oos_stats_available and in_sample_stats_available:
    print("\nVolatility (annualized):")
    print(f"  OOS Strategy: {oos_stats['Volatility (annualized)']:.6f} ({oos_stats['Volatility (annualized)']*100:.2f}%)")
    print(f"  In-Sample Strategy: {stats3['Volatility (annualized)']:.6f} ({stats3['Volatility (annualized)']*100:.2f}%)")
    print(f"  Market (SPY): {market_returns.std() * np.sqrt(12):.6f} ({market_returns.std() * np.sqrt(12)*100:.2f}%)")
    
    vol_diff = oos_stats['Volatility (annualized)'] - stats3['Volatility (annualized)']
    vol_diff_market = oos_stats['Volatility (annualized)'] - (market_returns.std() * np.sqrt(12))
    
    print(f"\n  OOS vs In-Sample: {vol_diff:+.6f} ({vol_diff*100:+.2f}%)")
    print(f"  OOS vs Market: {vol_diff_market:+.6f} ({vol_diff_market*100:+.2f}%)")
    
    print("\nVaR (5th percentile):")
    print(f"  OOS Strategy: {var_oos:.6f} ({var_oos*100:.2f}%)")
    print(f"  In-Sample Strategy: {var_in_sample:.6f} ({var_in_sample*100:.2f}%)")
    print(f"  Market (SPY): {var_market:.6f} ({var_market*100:.2f}%)")
    
    var_diff = var_oos - var_in_sample
    var_diff_market = var_oos - var_market
    
    print(f"\n  OOS vs In-Sample: {var_diff:+.6f} ({var_diff*100:+.2f}%)")
    print(f"  OOS vs Market: {var_diff_market:+.6f} ({var_diff_market*100:+.2f}%)")
    print(f"  (More negative = riskier)")
    
    print("\nMaximum Drawdown:")
    print(f"  OOS Strategy: {oos_stats['Max Drawdown']:.6f} ({oos_stats['Max Drawdown']*100:.2f}%)")
    print(f"  In-Sample Strategy: {stats3['Max Drawdown']:.6f} ({stats3['Max Drawdown']*100:.2f}%)")
    
    # Market max drawdown
    market_cumulative = (1 + market_returns).cumprod()
    market_running_max = market_cumulative.expanding().max()
    market_drawdown = (market_cumulative - market_running_max) / market_running_max
    market_max_dd = market_drawdown.min()
    
    print(f"  Market (SPY): {market_max_dd:.6f} ({market_max_dd*100:.2f}%)")
    
    dd_diff = oos_stats['Max Drawdown'] - stats3['Max Drawdown']
    dd_diff_market = oos_stats['Max Drawdown'] - market_max_dd
    
    print(f"\n  OOS vs In-Sample: {dd_diff:+.6f} ({dd_diff*100:+.2f}%)")
    print(f"  OOS vs Market: {dd_diff_market:+.6f} ({dd_diff_market*100:+.2f}%)")
    print(f"  (More negative = riskier)")
    
    print("\nMarket Beta:")
    print(f"  OOS Strategy: {oos_stats['Market Beta']:.6f}")
    print(f"  In-Sample Strategy: {stats3['Market Beta']:.6f}")
    print(f"  Market (SPY): 1.0 (by definition)")
    
    beta_diff = oos_stats['Market Beta'] - stats3['Market Beta']
    beta_diff_market = oos_stats['Market Beta'] - 1.0
    
    print(f"\n  OOS vs In-Sample: {beta_diff:+.6f}")
    print(f"  OOS vs Market: {beta_diff_market:+.6f}")
    print(f"  (Higher = riskier)")
    

RISK CHARACTERISTICS: OOS STRATEGY vs IN-SAMPLE STRATEGY

1. Monthly VaR at π = 0.05 (5th percentile)
OOS Strategy: -0.080101 (-8.01%)
In-Sample Strategy: -0.065591 (-6.56%)
Market (SPY): -0.098914 (-9.89%)
GMO (GMWAX): -0.077006 (-7.70%)

2. OOS Strategy Performance vs Risk-Free Rate (2000-2011)

Period: 2000-01-01 to 2011-12-31
Risk-free rate (monthly, average): 0.022875 (2.29%)

OOS Strategy:
  Mean monthly return: 0.017031 (1.70%)
  Mean excess over RF: -0.001095 (-0.11%)
  Cumulative excess return: -0.325721 (-32.57%)
  ✓ Underperforms risk-free rate

In-Sample Strategy:
  Mean monthly return: 0.078094 (7.81%)
  Mean excess over RF: 0.055218 (5.52%)
  Cumulative excess return: 643.748892 (64374.89%)
  ✗ Outperforms risk-free rate

3. Periods with Negative Risk Premium (OOS forecasts)

OOS Strategy:
  Periods with negative risk premium: 265 out of 286 (92.66%)

In-Sample Strategy (from section 3.3):
  Periods with negative risk premium: 231 out of 347 (66.57%)

4. Is the Point-in-T


The OOS strategy shows mixed risk characteristics.
  Some risk indicators suggest it's riskier (2 out of 4), but not consistently.
  Risk indicators: Worse VaR (more negative), Larger maximum drawdown

Comparison to Market:
  - OOS strategy has HIGHER volatility than market
  - OOS strategy has BETTER VaR than market (less risky)
  - OOS strategy has SMALLER maximum drawdown than market (less risky)
  - OOS strategy has LOWER beta than market (less risky)

## 5 EXTRA: ML Forecasts

1. **CART.** Re‑do Section 3 using **CART** (e.g., `RandomForestRegressor` from `sklearn.ensemble`). If you want to visualize, try `sklearn.tree`.


In [40]:
# ============================================================================
# 5. EXTRA: ML Forecasts - CART (RandomForestRegressor)
# Re-do Section 3 using CART instead of linear regression
# ============================================================================

from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor, plot_tree
import matplotlib.pyplot as plt

print("="*80)
print("ML FORECASTS: CART (RandomForestRegressor)")
print("="*80)
print("\nRe-doing Section 3 using RandomForestRegressor instead of linear regression")

# Align data
common_idx = signals.index.intersection(spy_excess.index)
signals_aligned = signals.loc[common_idx, [dp_col, ep_col, yield_col]]
spy_aligned = spy_excess.loc[common_idx]

signals_aligned = signals_aligned.sort_index()
spy_aligned = spy_aligned.sort_index()

valid_mask = ~(signals_aligned.isna().any(axis=1) | spy_aligned.isna())
signals_clean = signals_aligned[valid_mask]
spy_clean = spy_aligned[valid_mask]

print(f"\nData range: {spy_clean.index.min().date()} to {spy_clean.index.max().date()}")
print(f"Total observations: {len(spy_clean)}")

# ============================================================================
# 1. Lagged Regression using CART (RandomForestRegressor)
# ============================================================================

print("\n" + "="*80)
print("1. CART Regression: r^SPY_t = f(X_{t-1}) using RandomForestRegressor")
print("="*80)

# Function to perform lagged regression using RandomForest
def lagged_regression_cart(y, X, X_names, model_type='random_forest', n_estimators=100, max_depth=None):
    """
    Perform lagged regression using CART (RandomForest or DecisionTree).
    
    Parameters:
    y: Series of dependent variable (SPY returns at time t)
    X: DataFrame of predictors (at time t-1)
    X_names: List of predictor names
    model_type: 'random_forest' or 'decision_tree'
    n_estimators: Number of trees for RandomForest
    max_depth: Maximum depth of trees
    
    Returns:
    Dictionary with model, R², and other statistics
    """
    # Align indices - y at time t, X at time t-1
    X_lagged = X[X_names].shift(1)  # Shift forward so X[t-1] aligns with y[t]
    
    # Align indices
    common_idx = y.index.intersection(X_lagged.index)
    y_aligned = y.loc[common_idx]
    X_aligned = X_lagged.loc[common_idx]
    
    # Drop rows with NaN
    valid_mask = ~(X_aligned.isna().any(axis=1) | y_aligned.isna())
    y_clean = y_aligned[valid_mask]
    X_clean = X_aligned[valid_mask]
    
    if len(y_clean) == 0:
        return None
    
    # Prepare data
    X_values = X_clean.values
    y_values = y_clean.values
    
    # Fit CART model
    if model_type == 'random_forest':
        model = RandomForestRegressor(n_estimators=n_estimators, max_depth=max_depth, random_state=42)
    else:
        model = DecisionTreeRegressor(max_depth=max_depth, random_state=42)
    
    model.fit(X_values, y_values)
    
    # Get predictions
    y_pred = model.predict(X_values)
    
    # Calculate R-squared
    ss_res = np.sum((y_values - y_pred) ** 2)
    ss_tot = np.sum((y_values - np.mean(y_values)) ** 2)
    r_squared = 1 - (ss_res / ss_tot) if ss_tot != 0 else 0
    
    # Feature importance (for RandomForest)
    if model_type == 'random_forest':
        feature_importance = {name: imp for name, imp in zip(X_names, model.feature_importances_)}
    else:
        feature_importance = {name: 0 for name in X_names}  # DecisionTree doesn't have feature_importances_ in same way
    
    return {
        'Model': model,
        'Model Type': model_type,
        'R²': r_squared,
        'Feature Importance': feature_importance,
        'N observations': len(y_clean),
        'Predictions': y_pred,
        'Actual': y_values
    }

# Perform CART regressions for three cases (similar to Section 3.1)
print("\n1.1. CART Regression with DP only:")
print("-" * 80)
cart_reg1 = lagged_regression_cart(spy_clean, signals_clean, [dp_col], model_type='random_forest')
if cart_reg1:
    print(f"R²: {cart_reg1['R²']:.6f}")
    print(f"Feature Importance (DP): {cart_reg1['Feature Importance'][dp_col]:.6f}")
    print(f"N observations: {cart_reg1['N observations']}")
else:
    print("Regression failed")

print("\n1.2. CART Regression with EP only:")
print("-" * 80)
cart_reg2 = lagged_regression_cart(spy_clean, signals_clean, [ep_col], model_type='random_forest')
if cart_reg2:
    print(f"R²: {cart_reg2['R²']:.6f}")
    print(f"Feature Importance (EP): {cart_reg2['Feature Importance'][ep_col]:.6f}")
    print(f"N observations: {cart_reg2['N observations']}")
else:
    print("Regression failed")

print("\n1.3. CART Regression with DP, EP, and 10-year yield:")
print("-" * 80)
cart_reg3 = lagged_regression_cart(spy_clean, signals_clean, [dp_col, ep_col, yield_col], model_type='random_forest')
if cart_reg3:
    print(f"R²: {cart_reg3['R²']:.6f}")
    print(f"Feature Importance:")
    for name, imp in cart_reg3['Feature Importance'].items():
        print(f"  {name}: {imp:.6f}")
    print(f"N observations: {cart_reg3['N observations']}")
else:
    print("Regression failed")

# Summary table
print("\n" + "="*80)
print("SUMMARY: CART Regression R²")
print("="*80)
summary_cart = []
if cart_reg1:
    summary_cart.append({'Model': 'DP only (CART)', 'R²': cart_reg1['R²']})
if cart_reg2:
    summary_cart.append({'Model': 'EP only (CART)', 'R²': cart_reg2['R²']})
if cart_reg3:
    summary_cart.append({'Model': 'DP, EP, 10Y Yield (CART)', 'R²': cart_reg3['R²']})

if summary_cart:
    summary_cart_df = pd.DataFrame(summary_cart)
    print(summary_cart_df.to_string(index=False))
    
    # Compare with linear regression R² from Section 3
    print("\n" + "-" * 80)
    print("Comparison with Linear Regression (from Section 3):")
    if 'reg1' in globals() and reg1:
        print(f"  DP only - Linear: {reg1['R²']:.6f}, CART: {cart_reg1['R²']:.6f}, Difference: {cart_reg1['R²'] - reg1['R²']:+.6f}")
    if 'reg2' in globals() and reg2:
        print(f"  EP only - Linear: {reg2['R²']:.6f}, CART: {cart_reg2['R²']:.6f}, Difference: {cart_reg2['R²'] - reg2['R²']:+.6f}")
    if 'reg3' in globals() and reg3:
        print(f"  DP, EP, 10Y - Linear: {reg3['R²']:.6f}, CART: {cart_reg3['R²']:.6f}, Difference: {cart_reg3['R²'] - reg3['R²']:+.6f}")

# ============================================================================
# 2. Trading Strategy from CART Forecasts (re-do Section 3.2)
# ============================================================================

print("\n" + "="*80)
print("2. Trading Strategy from CART Forecasts (re-do Section 3.2)")
print("="*80)

# Function to build trading strategy from CART forecasts
def build_trading_strategy_cart(cart_reg_result, signals_df, spy_returns, X_names, strategy_name):
    """
    Build trading strategy from CART regression forecasts.
    Similar to build_trading_strategy but uses CART model.
    """
    if cart_reg_result is None:
        return None
    
    model = cart_reg_result['Model']
    
    # Align data - we need X_t to forecast r^{SPY}_{t+1}
    common_idx = signals_df.index.intersection(spy_returns.index)
    signals_aligned = signals_df.loc[common_idx, X_names]
    spy_aligned = spy_returns.loc[common_idx]
    
    # Shift spy_returns forward by 1 period so r^{SPY}_{t+1} aligns with X_t
    spy_next = spy_aligned.shift(-1)
    
    # Align again after shift
    common_idx_final = signals_aligned.index.intersection(spy_next.index)
    signals_final = signals_aligned.loc[common_idx_final]
    spy_next_final = spy_next.loc[common_idx_final]
    
    # Drop NaN
    valid_mask = ~(signals_final.isna().any(axis=1) | spy_next_final.isna())
    signals_clean = signals_final[valid_mask]
    spy_next_clean = spy_next_final[valid_mask]
    
    if len(signals_clean) == 0:
        return None
    
    # Build forecasts using CART model
    X_values = signals_clean.values
    forecasts = model.predict(X_values)
    
    # Portfolio weights: w_t = 100 * r̂^{SPY}_{t+1}
    weights = 100 * forecasts
    
    # Strategy returns: r^x_{t+1} = w_t * r^{SPY}_{t+1}
    strategy_returns = weights * spy_next_clean.values
    
    # Create Series
    strategy_returns_series = pd.Series(strategy_returns, index=signals_clean.index)
    
    return {
        'strategy_name': strategy_name,
        'forecasts': pd.Series(forecasts, index=signals_clean.index),
        'weights': pd.Series(weights, index=signals_clean.index),
        'strategy_returns': strategy_returns_series,
        'spy_returns': spy_next_clean
    }

# Build strategies for all three CART models
print("\nBuilding CART trading strategies...")

# Strategy 1: DP only (CART)
cart_strategy1 = build_trading_strategy_cart(cart_reg1, signals_clean, spy_clean, [dp_col], 'DP only (CART)')
cart_stats1 = calculate_strategy_stats(cart_strategy1, spy_excess) if cart_strategy1 else None

# Strategy 2: EP only (CART)
cart_strategy2 = build_trading_strategy_cart(cart_reg2, signals_clean, spy_clean, [ep_col], 'EP only (CART)')
cart_stats2 = calculate_strategy_stats(cart_strategy2, spy_excess) if cart_strategy2 else None

# Strategy 3: DP, EP, 10Y Yield (CART)
cart_strategy3 = build_trading_strategy_cart(cart_reg3, signals_clean, spy_clean, [dp_col, ep_col, yield_col], 'DP, EP, 10Y Yield (CART)')
cart_stats3 = calculate_strategy_stats(cart_strategy3, spy_excess) if cart_strategy3 else None

# Display results
print("\n" + "="*80)
print("CART STRATEGY STATISTICS")
print("="*80)

for i, (cart_strat, cart_stat, name) in enumerate([(cart_strategy1, cart_stats1, 'DP only (CART)'),
                                                    (cart_strategy2, cart_stats2, 'EP only (CART)'),
                                                    (cart_strategy3, cart_stats3, 'DP, EP, 10Y Yield (CART)')], 1):
    print(f"\nStrategy {i}: {name}")
    print("-" * 80)
    if cart_stat:
        for key, value in cart_stat.items():
            if isinstance(value, float):
                print(f"{key}: {value:.6f}")
            else:
                print(f"{key}: {value}")
    else:
        print("Strategy calculation failed")

# Summary table comparing CART with linear regression
print("\n" + "="*80)
print("COMPARISON: CART vs Linear Regression Strategies")
print("="*80)
print("\nFocusing on Strategy 3 (DP, EP, 10Y Yield) for comparison:")

if cart_stats3 and 'stats3' in globals() and stats3:
    print("\nMean Return (annualized):")
    print(f"  CART: {cart_stats3['Mean (annualized)']:.6f}")
    print(f"  Linear: {stats3['Mean (annualized)']:.6f}")
    print(f"  Difference: {cart_stats3['Mean (annualized)'] - stats3['Mean (annualized)']:+.6f}")
    
    print("\nVolatility (annualized):")
    print(f"  CART: {cart_stats3['Volatility (annualized)']:.6f}")
    print(f"  Linear: {stats3['Volatility (annualized)']:.6f}")
    print(f"  Difference: {cart_stats3['Volatility (annualized)'] - stats3['Volatility (annualized)']:+.6f}")
    
    print("\nSharpe Ratio (annualized):")
    print(f"  CART: {cart_stats3['Sharpe Ratio (annualized)']:.6f}")
    print(f"  Linear: {stats3['Sharpe Ratio (annualized)']:.6f}")
    print(f"  Difference: {cart_stats3['Sharpe Ratio (annualized)'] - stats3['Sharpe Ratio (annualized)']:+.6f}")
    
    print("\nMaximum Drawdown:")
    print(f"  CART: {cart_stats3['Max Drawdown']:.6f}")
    print(f"  Linear: {stats3['Max Drawdown']:.6f}")
    print(f"  Difference: {cart_stats3['Max Drawdown'] - stats3['Max Drawdown']:+.6f}")
    
    print("\nMarket Alpha:")
    print(f"  CART: {cart_stats3['Market Alpha']:.6f}")
    print(f"  Linear: {stats3['Market Alpha']:.6f}")
    print(f"  Difference: {cart_stats3['Market Alpha'] - stats3['Market Alpha']:+.6f}")
    
    print("\nMarket Beta:")
    print(f"  CART: {cart_stats3['Market Beta']:.6f}")
    print(f"  Linear: {stats3['Market Beta']:.6f}")
    print(f"  Difference: {cart_stats3['Market Beta'] - stats3['Market Beta']:+.6f}")
    
    print("\nInformation Ratio (annualized):")
    print(f"  CART: {cart_stats3['Information Ratio (annualized)']:.6f}")
    print(f"  Linear: {stats3['Information Ratio (annualized)']:.6f}")
    print(f"  Difference: {cart_stats3['Information Ratio (annualized)'] - stats3['Information Ratio (annualized)']:+.6f}")

# ============================================================================
# 3. Risk Characteristics (re-do Section 3.3)
# ============================================================================

print("\n" + "="*80)
print("3. Risk Characteristics for CART Strategies (re-do Section 3.3)")
print("="*80)

# VaR calculation
print("\nMonthly VaR at π = 0.05:")
print("-" * 80)
if cart_strategy1:
    var_cart1 = calculate_var(cart_strategy1['strategy_returns'], 0.05)
    print(f"Strategy 1 (DP only, CART): {var_cart1:.6f} ({var_cart1*100:.2f}%)")
if cart_strategy2:
    var_cart2 = calculate_var(cart_strategy2['strategy_returns'], 0.05)
    print(f"Strategy 2 (EP only, CART): {var_cart2:.6f} ({var_cart2*100:.2f}%)")
if cart_strategy3:
    var_cart3 = calculate_var(cart_strategy3['strategy_returns'], 0.05)
    print(f"Strategy 3 (DP, EP, 10Y, CART): {var_cart3:.6f} ({var_cart3*100:.2f}%)")

# Compare with linear regression strategies
if 'var_strategy1' in globals() and not np.isnan(var_strategy1):
    print(f"\nComparison with Linear Regression:")
    if cart_strategy1:
        print(f"  DP only - Linear: {var_strategy1:.6f}, CART: {var_cart1:.6f}")
    if cart_strategy2:
        print(f"  EP only - Linear: {var_strategy2:.6f}, CART: {var_cart2:.6f}")
    if cart_strategy3:
        print(f"  DP, EP, 10Y - Linear: {var_strategy3:.6f}, CART: {var_cart3:.6f}")

print("\n" + "="*80)
print("CART IMPLEMENTATION COMPLETE")
print("="*80)
print("\nNote: CART (RandomForest) can capture non-linear relationships that linear regression cannot.")
print("However, it may also be more prone to overfitting, especially with small datasets.")


ML FORECASTS: CART (RandomForestRegressor)

Re-doing Section 3 using RandomForestRegressor instead of linear regression

Data range: 1996-12-31 to 2025-10-31
Total observations: 347

1. CART Regression: r^SPY_t = f(X_{t-1}) using RandomForestRegressor

1.1. CART Regression with DP only:
--------------------------------------------------------------------------------
R²: 0.805219
Feature Importance (DP): 1.000000
N observations: 346

1.2. CART Regression with EP only:
--------------------------------------------------------------------------------
R²: 0.805305
Feature Importance (EP): 1.000000
N observations: 346

1.3. CART Regression with DP, EP, and 10-year yield:
--------------------------------------------------------------------------------
R²: 0.872010
Feature Importance:
  SPX D/P: 0.320564
  SPX E/P: 0.261813
  T-Note 10YR: 0.417624
N observations: 346

SUMMARY: CART Regression R²
                   Model       R²
          DP only (CART) 0.805219
          EP only (CART) 0.8053

2. **CART, OOS.** Compute out‑of‑sample stats as in Section 4.


In [45]:
# ============================================================================
# 2. CART, OOS - Compute out-of-sample stats as in Section 4
# Focus on using both DP and EP as signals (using CART)
# ============================================================================

print("="*80)
print("OUT-OF-SAMPLE FORECASTING: CART (RandomForestRegressor)")
print("="*80)
print("\nUsing both DP and EP as signals for CART forecasting")

# Align data (focus on DP and EP, as in Section 4)
common_idx = signals.index.intersection(spy_excess.index)
signals_aligned = signals.loc[common_idx, [dp_col, ep_col]]
spy_aligned = spy_excess.loc[common_idx]

# Sort by date
signals_aligned = signals_aligned.sort_index()
spy_aligned = spy_aligned.sort_index()

# Remove NaN rows
valid_mask = ~(signals_aligned.isna().any(axis=1) | spy_aligned.isna())
signals_clean = signals_aligned[valid_mask]
spy_clean = spy_aligned[valid_mask]

print(f"\nData range: {spy_clean.index.min().date()} to {spy_clean.index.max().date()}")
print(f"Total observations: {len(spy_clean)}")
print(f"Starting OOS at t=60 (observation {spy_clean.index[60]})")

# Initialize storage for forecasts and errors
cart_forecast_errors = []
cart_null_errors = []
cart_forecast_values = []
cart_null_forecast_values = []
cart_actual_returns = []

# Rolling out-of-sample procedure using CART
start_idx = 60
T = len(spy_clean)

print(f"\nRunning rolling OOS procedure with CART from t={start_idx} to t={T-2}...")

for t in range(start_idx, T - 1):
    # Data through time t (for estimation)
    spy_train = spy_clean.iloc[:t+1]
    signals_train = signals_clean.iloc[:t+1]
    
    # X_t (predictors at time t) for forecasting
    x_t = signals_clean.iloc[t:t+1]
    
    # r^{SPY}_{t+1} (actual return at time t+1)
    r_t_plus_1 = spy_clean.iloc[t+1]
    
    # Drop NaN from training data
    train_mask = ~(signals_train.isna().any(axis=1) | spy_train.isna())
    signals_train_clean = signals_train[train_mask]
    spy_train_clean = spy_train[train_mask]
    
    if len(signals_train_clean) < 2:
        continue
    
    # Estimate CART regression using data through time t
    # r^{SPY}_i = f(X_{i-1}) for i = 1 to t
    # We need to lag the signals
    signals_train_lagged = signals_train_clean.shift(1).iloc[1:]  # X_{i-1}
    spy_train_aligned = spy_train_clean.iloc[1:]  # r^{SPY}_i
    
    # Align after lag
    common_train_idx = signals_train_lagged.index.intersection(spy_train_aligned.index)
    signals_train_final = signals_train_lagged.loc[common_train_idx]
    spy_train_final = spy_train_aligned.loc[common_train_idx]
    
    if len(signals_train_final) < 2:
        continue
    
    # Fit CART model (RandomForestRegressor)
    X_train = signals_train_final.values
    y_train = spy_train_final.values
    
    # Use RandomForestRegressor with reasonable parameters
    cart_model = RandomForestRegressor(n_estimators=100, max_depth=5, random_state=42)
    cart_model.fit(X_train, y_train)
    
    # Forecast r^{SPY}_{t+1} using x_t
    x_t_values = x_t.values
    forecast = cart_model.predict(x_t_values)[0]
    
    # Forecast error
    forecast_error = r_t_plus_1 - forecast
    
    # Null forecast: mean of returns through time t
    null_forecast = spy_train_clean.mean()
    null_error = r_t_plus_1 - null_forecast
    
    # Store results
    cart_forecast_errors.append(forecast_error)
    cart_null_errors.append(null_error)
    cart_forecast_values.append(forecast)
    cart_null_forecast_values.append(null_forecast)
    cart_actual_returns.append(r_t_plus_1)

# Convert to arrays
cart_forecast_errors = np.array(cart_forecast_errors)
cart_null_errors = np.array(cart_null_errors)

# Calculate out-of-sample R²
sum_squared_cart_forecast_errors = np.sum(cart_forecast_errors ** 2)
sum_squared_cart_null_errors = np.sum(cart_null_errors ** 2)

if sum_squared_cart_null_errors > 0:
    cart_r2_oos = 1 - (sum_squared_cart_forecast_errors / sum_squared_cart_null_errors)
else:
    cart_r2_oos = np.nan

# Display results
print("\n" + "="*80)
print("OUT-OF-SAMPLE RESULTS: CART")
print("="*80)
print(f"\nNumber of OOS forecasts: {len(cart_forecast_errors)}")
print(f"Sum of squared forecast errors: {sum_squared_cart_forecast_errors:.6f}")
print(f"Sum of squared null errors: {sum_squared_cart_null_errors:.6f}")
print(f"\nOut-of-Sample R² (CART): {cart_r2_oos:.6f}")

if cart_r2_oos > 0:
    print(f"\n✓ YES - The CART forecasting strategy produced a POSITIVE R²_OOS ({cart_r2_oos:.6f})")
    print("  This means the CART model forecasts are better than the null (mean) forecast.")
elif cart_r2_oos < 0:
    print(f"\n✗ NO - The CART forecasting strategy produced a NEGATIVE R²_OOS ({cart_r2_oos:.6f})")
    print("  This means the CART model forecasts are worse than the null (mean) forecast.")
else:
    print(f"\nThe CART forecasting strategy produced R²_OOS = 0")
    print("  This means the CART model forecasts perform the same as the null (mean) forecast.")

# Compare with linear regression OOS R² from Section 4
if 'r2_oos' in globals() and not np.isnan(r2_oos):
    print("\n" + "="*80)
    print("COMPARISON: CART vs Linear Regression (OOS)")
    print("="*80)
    print(f"Linear Regression R²_OOS: {r2_oos:.6f}")
    print(f"CART R²_OOS: {cart_r2_oos:.6f}")
    print(f"Difference: {cart_r2_oos - r2_oos:+.6f}")
    
    if cart_r2_oos > r2_oos:
        print("\n✓ CART outperforms linear regression out-of-sample")
    elif cart_r2_oos < r2_oos:
        print("\n✗ Linear regression outperforms CART out-of-sample")
    else:
        print("\n= CART and linear regression perform similarly out-of-sample")

# Additional statistics
print("\n" + "="*80)
print("ADDITIONAL STATISTICS: CART OOS")
print("="*80)
print(f"Mean forecast error: {np.mean(cart_forecast_errors):.6f}")
print(f"RMSE (forecast): {np.sqrt(np.mean(cart_forecast_errors**2)):.6f}")
print(f"Mean null error: {np.mean(cart_null_errors):.6f}")
print(f"RMSE (null): {np.sqrt(np.mean(cart_null_errors**2)):.6f}")

if np.sqrt(np.mean(cart_forecast_errors**2)) < np.sqrt(np.mean(cart_null_errors**2)):
    improvement = ((np.sqrt(np.mean(cart_null_errors**2)) - np.sqrt(np.mean(cart_forecast_errors**2))) / 
                   np.sqrt(np.mean(cart_null_errors**2))) * 100
    print(f"\nCART forecast RMSE is {improvement:.2f}% lower than null forecast RMSE")
else:
    deterioration = ((np.sqrt(np.mean(cart_forecast_errors**2)) - np.sqrt(np.mean(cart_null_errors**2))) / 
                     np.sqrt(np.mean(cart_null_errors**2))) * 100
    print(f"\nCART forecast RMSE is {deterioration:.2f}% higher than null forecast RMSE")

# Compare RMSE with linear regression
if 'forecast_errors' in globals() and len(forecast_errors) > 0:
    linear_rmse = np.sqrt(np.mean(forecast_errors**2))
    cart_rmse = np.sqrt(np.mean(cart_forecast_errors**2))
    print(f"\nRMSE Comparison:")
    print(f"  Linear Regression: {linear_rmse:.6f}")
    print(f"  CART: {cart_rmse:.6f}")
    print(f"  Difference: {cart_rmse - linear_rmse:+.6f}")
    
    if cart_rmse < linear_rmse:
        improvement_pct = ((linear_rmse - cart_rmse) / linear_rmse) * 100
        print(f"  CART RMSE is {improvement_pct:.2f}% lower (better)")
    else:
        deterioration_pct = ((cart_rmse - linear_rmse) / linear_rmse) * 100
        print(f"  CART RMSE is {deterioration_pct:.2f}% higher (worse)")


OUT-OF-SAMPLE FORECASTING: CART (RandomForestRegressor)

Using both DP and EP as signals for CART forecasting

Data range: 1996-12-31 to 2025-10-31
Total observations: 347
Starting OOS at t=60 (observation 2001-12-31 00:00:00)

Running rolling OOS procedure with CART from t=60 to t=345...

OUT-OF-SAMPLE RESULTS: CART

Number of OOS forecasts: 286
Sum of squared forecast errors: 0.660284
Sum of squared null errors: 0.663985

Out-of-Sample R² (CART): 0.005575

✓ YES - The CART forecasting strategy produced a POSITIVE R²_OOS (0.005575)
  This means the CART model forecasts are better than the null (mean) forecast.

COMPARISON: CART vs Linear Regression (OOS)
Linear Regression R²_OOS: 0.088220
CART R²_OOS: 0.005575
Difference: -0.082645

✗ Linear regression outperforms CART out-of-sample

ADDITIONAL STATISTICS: CART OOS
Mean forecast error: 0.006538
RMSE (forecast): 0.048049
Mean null error: 0.013239
RMSE (null): 0.048183

CART forecast RMSE is 0.28% lower than null forecast RMSE

RMSE Com

3. **Neural Network.** Re‑do Section 3 using a **neural network** (e.g., `MLPRegressor` from `sklearn.neural_network`).


In [48]:

# ============================================================================
# 3. Neural Network - Re-do Section 3 using MLPRegressor
# ============================================================================

from sklearn.neural_network import MLPRegressor

print("="*80)
print("ML FORECASTS: NEURAL NETWORK (MLPRegressor)")
print("="*80)
print("\nRe-doing Section 3 using MLPRegressor instead of linear regression")

# Align data
common_idx = signals.index.intersection(spy_excess.index)
signals_aligned = signals.loc[common_idx, [dp_col, ep_col, yield_col]]
spy_aligned = spy_excess.loc[common_idx]

signals_aligned = signals_aligned.sort_index()
spy_aligned = spy_aligned.sort_index()

valid_mask = ~(signals_aligned.isna().any(axis=1) | spy_aligned.isna())
signals_clean = signals_aligned[valid_mask]
spy_clean = spy_aligned[valid_mask]

print(f"\nData range: {spy_clean.index.min().date()} to {spy_clean.index.max().date()}")
print(f"Total observations: {len(spy_clean)}")

# ============================================================================
# 1. Lagged Regression using Neural Network (MLPRegressor)
# ============================================================================

print("\n" + "="*80)
print("1. Neural Network Regression: r^SPY_t = f(X_{t-1}) using MLPRegressor")
print("="*80)

# Function to perform lagged regression using Neural Network
def lagged_regression_nn(y, X, X_names, hidden_layer_sizes=(50,), max_iter=500, random_state=42):
    """
    Perform lagged regression using Neural Network (MLPRegressor).
    
    Parameters:
    y: Series of dependent variable (SPY returns at time t)
    X: DataFrame of predictors (at time t-1)
    X_names: List of predictor names
    hidden_layer_sizes: Tuple of hidden layer sizes
    max_iter: Maximum iterations for training
    random_state: Random state for reproducibility
    
    Returns:
    Dictionary with model, R², and other statistics
    """
    # Align indices - y at time t, X at time t-1
    X_lagged = X[X_names].shift(1)  # Shift forward so X[t-1] aligns with y[t]
    
    # Align indices
    common_idx = y.index.intersection(X_lagged.index)
    y_aligned = y.loc[common_idx]
    X_aligned = X_lagged.loc[common_idx]
    
    # Drop rows with NaN
    valid_mask = ~(X_aligned.isna().any(axis=1) | y_aligned.isna())
    y_clean = y_aligned[valid_mask]
    X_clean = X_aligned[valid_mask]
    
    if len(y_clean) == 0:
        return None
    
    # Prepare data
    X_values = X_clean.values
    y_values = y_clean.values
    
    # Fit Neural Network model
    # Use a simple architecture: one hidden layer with 50 neurons
    nn_model = MLPRegressor(hidden_layer_sizes=hidden_layer_sizes, 
                            max_iter=max_iter, 
                            random_state=random_state,
                            early_stopping=True,
                            validation_fraction=0.1)
    
    try:
        nn_model.fit(X_values, y_values)
    except Exception as e:
        print(f"Warning: Neural network fitting failed: {e}")
        return None
    
    # Get predictions
    y_pred = nn_model.predict(X_values)
    
    # Calculate R-squared
    ss_res = np.sum((y_values - y_pred) ** 2)
    ss_tot = np.sum((y_values - np.mean(y_values)) ** 2)
    r_squared = 1 - (ss_res / ss_tot) if ss_tot != 0 else 0
    
    return {
        'Model': nn_model,
        'Model Type': 'Neural Network (MLP)',
        'R²': r_squared,
        'N observations': len(y_clean),
        'Predictions': y_pred,
        'Actual': y_values,
        'N iterations': nn_model.n_iter_ if hasattr(nn_model, 'n_iter_') else None
    }

# Perform Neural Network regressions for three cases
print("\n1.1. Neural Network Regression with DP only:")
print("-" * 80)
nn_reg1 = lagged_regression_nn(spy_clean, signals_clean, [dp_col], hidden_layer_sizes=(50,))
if nn_reg1:
    print(f"R²: {nn_reg1['R²']:.6f}")
    print(f"N observations: {nn_reg1['N observations']}")
    if nn_reg1['N iterations']:
        print(f"Training iterations: {nn_reg1['N iterations']}")
else:
    print("Regression failed")

print("\n1.2. Neural Network Regression with EP only:")
print("-" * 80)
nn_reg2 = lagged_regression_nn(spy_clean, signals_clean, [ep_col], hidden_layer_sizes=(50,))
if nn_reg2:
    print(f"R²: {nn_reg2['R²']:.6f}")
    print(f"N observations: {nn_reg2['N observations']}")
    if nn_reg2['N iterations']:
        print(f"Training iterations: {nn_reg2['N iterations']}")
else:
    print("Regression failed")

print("\n1.3. Neural Network Regression with DP, EP, and 10-year yield:")
print("-" * 80)
nn_reg3 = lagged_regression_nn(spy_clean, signals_clean, [dp_col, ep_col, yield_col], hidden_layer_sizes=(50,))
if nn_reg3:
    print(f"R²: {nn_reg3['R²']:.6f}")
    print(f"N observations: {nn_reg3['N observations']}")
    if nn_reg3['N iterations']:
        print(f"Training iterations: {nn_reg3['N iterations']}")
else:
    print("Regression failed")

# Summary table
print("\n" + "="*80)
print("SUMMARY: Neural Network Regression R²")
print("="*80)
summary_nn = []
if nn_reg1:
    summary_nn.append({'Model': 'DP only (NN)', 'R²': nn_reg1['R²']})
if nn_reg2:
    summary_nn.append({'Model': 'EP only (NN)', 'R²': nn_reg2['R²']})
if nn_reg3:
    summary_nn.append({'Model': 'DP, EP, 10Y Yield (NN)', 'R²': nn_reg3['R²']})

if summary_nn:
    summary_nn_df = pd.DataFrame(summary_nn)
    print(summary_nn_df.to_string(index=False))
    
    # Compare with linear regression R² from Section 3
    print("\n" + "-" * 80)
    print("Comparison with Linear Regression (from Section 3):")
    if 'reg1' in globals() and reg1:
        print(f"  DP only - Linear: {reg1['R²']:.6f}, NN: {nn_reg1['R²']:.6f}, Difference: {nn_reg1['R²'] - reg1['R²']:+.6f}")
    if 'reg2' in globals() and reg2:
        print(f"  EP only - Linear: {reg2['R²']:.6f}, NN: {nn_reg2['R²']:.6f}, Difference: {nn_reg2['R²'] - reg2['R²']:+.6f}")
    if 'reg3' in globals() and reg3:
        print(f"  DP, EP, 10Y - Linear: {reg3['R²']:.6f}, NN: {nn_reg3['R²']:.6f}, Difference: {nn_reg3['R²'] - reg3['R²']:+.6f}")

# ============================================================================
# 2. Trading Strategy from Neural Network Forecasts (re-do Section 3.2)
# ============================================================================

print("\n" + "="*80)
print("2. Trading Strategy from Neural Network Forecasts (re-do Section 3.2)")
print("="*80)

# Function to build trading strategy from Neural Network forecasts
def build_trading_strategy_nn(nn_reg_result, signals_df, spy_returns, X_names, strategy_name):
    """
    Build trading strategy from Neural Network regression forecasts.
    Similar to build_trading_strategy but uses Neural Network model.
    """
    if nn_reg_result is None:
        return None
    
    model = nn_reg_result['Model']
    
    # Align data - we need X_t to forecast r^{SPY}_{t+1}
    common_idx = signals_df.index.intersection(spy_returns.index)
    signals_aligned = signals_df.loc[common_idx, X_names]
    spy_aligned = spy_returns.loc[common_idx]
    
    # Shift spy_returns forward by 1 period so r^{SPY}_{t+1} aligns with X_t
    spy_next = spy_aligned.shift(-1)
    
    # Align again after shift
    common_idx_final = signals_aligned.index.intersection(spy_next.index)
    signals_final = signals_aligned.loc[common_idx_final]
    spy_next_final = spy_next.loc[common_idx_final]
    
    # Drop NaN
    valid_mask = ~(signals_final.isna().any(axis=1) | spy_next_final.isna())
    signals_clean = signals_final[valid_mask]
    spy_next_clean = spy_next_final[valid_mask]
    
    if len(signals_clean) == 0:
        return None
    
    # Build forecasts using Neural Network model
    X_values = signals_clean.values
    forecasts = model.predict(X_values)
    
    # Portfolio weights: w_t = 100 * r̂^{SPY}_{t+1}
    weights = 100 * forecasts
    
    # Strategy returns: r^x_{t+1} = w_t * r^{SPY}_{t+1}
    strategy_returns = weights * spy_next_clean.values
    
    # Create Series
    strategy_returns_series = pd.Series(strategy_returns, index=signals_clean.index)
    
    return {
        'strategy_name': strategy_name,
        'forecasts': pd.Series(forecasts, index=signals_clean.index),
        'weights': pd.Series(weights, index=signals_clean.index),
        'strategy_returns': strategy_returns_series,
        'spy_returns': spy_next_clean
    }

# Build strategies for all three Neural Network models
print("\nBuilding Neural Network trading strategies...")

# Strategy 1: DP only (NN)
nn_strategy1 = build_trading_strategy_nn(nn_reg1, signals_clean, spy_clean, [dp_col], 'DP only (NN)')
nn_stats1 = calculate_strategy_stats(nn_strategy1, spy_excess) if nn_strategy1 else None

# Strategy 2: EP only (NN)
nn_strategy2 = build_trading_strategy_nn(nn_reg2, signals_clean, spy_clean, [ep_col], 'EP only (NN)')
nn_stats2 = calculate_strategy_stats(nn_strategy2, spy_excess) if nn_strategy2 else None

# Strategy 3: DP, EP, 10Y Yield (NN)
nn_strategy3 = build_trading_strategy_nn(nn_reg3, signals_clean, spy_clean, [dp_col, ep_col, yield_col], 'DP, EP, 10Y Yield (NN)')
nn_stats3 = calculate_strategy_stats(nn_strategy3, spy_excess) if nn_strategy3 else None

# Display results
print("\n" + "="*80)
print("NEURAL NETWORK STRATEGY STATISTICS")
print("="*80)

for i, (nn_strat, nn_stat, name) in enumerate([(nn_strategy1, nn_stats1, 'DP only (NN)'),
                                                 (nn_strategy2, nn_stats2, 'EP only (NN)'),
                                                 (nn_strategy3, nn_stats3, 'DP, EP, 10Y Yield (NN)')], 1):
    print(f"\nStrategy {i}: {name}")
    print("-" * 80)
    if nn_stat:
        for key, value in nn_stat.items():
            if isinstance(value, float):
                print(f"{key}: {value:.6f}")
            else:
                print(f"{key}: {value}")
    else:
        print("Strategy calculation failed")

# Summary table comparing Neural Network with linear regression
print("\n" + "="*80)
print("COMPARISON: Neural Network vs Linear Regression Strategies")
print("="*80)
print("\nFocusing on Strategy 3 (DP, EP, 10Y Yield) for comparison:")

if nn_stats3 and 'stats3' in globals() and stats3:
    print("\nMean Return (annualized):")
    print(f"  Neural Network: {nn_stats3['Mean (annualized)']:.6f}")
    print(f"  Linear: {stats3['Mean (annualized)']:.6f}")
    print(f"  Difference: {nn_stats3['Mean (annualized)'] - stats3['Mean (annualized)']:+.6f}")
    
    print("\nVolatility (annualized):")
    print(f"  Neural Network: {nn_stats3['Volatility (annualized)']:.6f}")
    print(f"  Linear: {stats3['Volatility (annualized)']:.6f}")
    print(f"  Difference: {nn_stats3['Volatility (annualized)'] - stats3['Volatility (annualized)']:+.6f}")
    
    print("\nSharpe Ratio (annualized):")
    print(f"  Neural Network: {nn_stats3['Sharpe Ratio (annualized)']:.6f}")
    print(f"  Linear: {stats3['Sharpe Ratio (annualized)']:.6f}")
    print(f"  Difference: {nn_stats3['Sharpe Ratio (annualized)'] - stats3['Sharpe Ratio (annualized)']:+.6f}")
    
    print("\nMaximum Drawdown:")
    print(f"  Neural Network: {nn_stats3['Max Drawdown']:.6f}")
    print(f"  Linear: {stats3['Max Drawdown']:.6f}")
    print(f"  Difference: {nn_stats3['Max Drawdown'] - stats3['Max Drawdown']:+.6f}")
    
    print("\nMarket Alpha:")
    print(f"  Neural Network: {nn_stats3['Market Alpha']:.6f}")
    print(f"  Linear: {stats3['Market Alpha']:.6f}")
    print(f"  Difference: {nn_stats3['Market Alpha'] - stats3['Market Alpha']:+.6f}")
    
    print("\nMarket Beta:")
    print(f"  Neural Network: {nn_stats3['Market Beta']:.6f}")
    print(f"  Linear: {stats3['Market Beta']:.6f}")
    print(f"  Difference: {nn_stats3['Market Beta'] - stats3['Market Beta']:+.6f}")
    
    print("\nInformation Ratio (annualized):")
    print(f"  Neural Network: {nn_stats3['Information Ratio (annualized)']:.6f}")
    print(f"  Linear: {stats3['Information Ratio (annualized)']:.6f}")
    print(f"  Difference: {nn_stats3['Information Ratio (annualized)'] - stats3['Information Ratio (annualized)']:+.6f}")

# ============================================================================
# 3. Risk Characteristics (re-do Section 3.3)
# ============================================================================

print("\n" + "="*80)
print("3. Risk Characteristics for Neural Network Strategies (re-do Section 3.3)")
print("="*80)

# VaR calculation
print("\nMonthly VaR at π = 0.05:")
print("-" * 80)
if nn_strategy1:
    var_nn1 = calculate_var(nn_strategy1['strategy_returns'], 0.05)
    print(f"Strategy 1 (DP only, NN): {var_nn1:.6f} ({var_nn1*100:.2f}%)")
if nn_strategy2:
    var_nn2 = calculate_var(nn_strategy2['strategy_returns'], 0.05)
    print(f"Strategy 2 (EP only, NN): {var_nn2:.6f} ({var_nn2*100:.2f}%)")
if nn_strategy3:
    var_nn3 = calculate_var(nn_strategy3['strategy_returns'], 0.05)
    print(f"Strategy 3 (DP, EP, 10Y, NN): {var_nn3:.6f} ({var_nn3*100:.2f}%)")

# Compare with linear regression strategies
if 'var_strategy1' in globals() and not np.isnan(var_strategy1):
    print(f"\nComparison with Linear Regression:")
    if nn_strategy1:
        print(f"  DP only - Linear: {var_strategy1:.6f}, NN: {var_nn1:.6f}")
    if nn_strategy2:
        print(f"  EP only - Linear: {var_strategy2:.6f}, NN: {var_nn2:.6f}")
    if nn_strategy3:
        print(f"  DP, EP, 10Y - Linear: {var_strategy3:.6f}, NN: {var_nn3:.6f}")

print("\n" + "="*80)
print("NEURAL NETWORK IMPLEMENTATION COMPLETE")
print("="*80)
print("\nNote: Neural Networks can capture complex non-linear relationships.")
print("However, they require careful tuning and may be prone to overfitting.")

ML FORECASTS: NEURAL NETWORK (MLPRegressor)

Re-doing Section 3 using MLPRegressor instead of linear regression

Data range: 1996-12-31 to 2025-10-31
Total observations: 347

1. Neural Network Regression: r^SPY_t = f(X_{t-1}) using MLPRegressor

1.1. Neural Network Regression with DP only:
--------------------------------------------------------------------------------
R²: -0.089096
N observations: 346
Training iterations: 14

1.2. Neural Network Regression with EP only:
--------------------------------------------------------------------------------
R²: -0.053294
N observations: 346
Training iterations: 14

1.3. Neural Network Regression with DP, EP, and 10-year yield:
--------------------------------------------------------------------------------
R²: 0.015730
N observations: 346
Training iterations: 30

SUMMARY: Neural Network Regression R²
                 Model        R²
          DP only (NN) -0.089096
          EP only (NN) -0.053294
DP, EP, 10Y Yield (NN)  0.015730

-----------

4. **NN & CART, OOS.** Compute out‑of‑sample stats as in Section 4.

In [49]:
# ============================================================================
# 4. NN & CART, OOS - Compute out-of-sample stats as in Section 4
# ============================================================================

from sklearn.neural_network import MLPRegressor
from sklearn.ensemble import RandomForestRegressor

print("="*80)
print("OUT-OF-SAMPLE FORECASTING: NEURAL NETWORK & CART")
print("="*80)
print("\nUsing both DP and EP as signals for forecasting")
print("Comparing Neural Network (MLPRegressor) and CART (RandomForestRegressor)")

# Align data
common_idx = signals.index.intersection(spy_excess.index)
signals_aligned = signals.loc[common_idx, [dp_col, ep_col]]
spy_aligned = spy_excess.loc[common_idx]

# Sort by date to ensure proper ordering
signals_aligned = signals_aligned.sort_index()
spy_aligned = spy_aligned.sort_index()

# Drop rows with NaN
valid_mask = ~(signals_aligned.isna().any(axis=1) | spy_aligned.isna())
signals_clean = signals_aligned[valid_mask]
spy_clean = spy_aligned[valid_mask]

print(f"\nData range: {spy_clean.index.min().date()} to {spy_clean.index.max().date()}")
print(f"Total observations: {len(spy_clean)}")

# Initialize OOS procedure
start_idx = 60
T = len(spy_clean)

print(f"\nStarting OOS at t={start_idx} (observation {spy_clean.index[start_idx]})")
print(f"Running rolling OOS procedure from t={start_idx} to t={T-2}...")

# ============================================================================
# 1. Neural Network OOS Forecasting
# ============================================================================

print("\n" + "="*80)
print("1. NEURAL NETWORK (MLPRegressor) OUT-OF-SAMPLE FORECASTING")
print("="*80)

# Initialize storage for NN forecasts and errors
nn_forecast_errors = []
nn_null_errors = []
nn_forecast_values = []
nn_null_forecast_values = []
nn_actual_returns = []
nn_forecast_dates = []

# Rolling out-of-sample procedure for Neural Network
for t in range(start_idx, T - 1):
    # Data through time t (for estimation)
    spy_train = spy_clean.iloc[:t+1]
    signals_train = signals_clean.iloc[:t+1]
    
    # Create lagged data: X_{t-1} predicts r_t
    # For training: we need X_{i-1} to predict r_i for i=1 to t
    X_train_lagged = signals_train.shift(1).iloc[1:]  # X_{0} to X_{t-1}
    y_train = spy_train.iloc[1:t+1]  # r_1 to r_t
    
    # Align indices
    common_train_idx = X_train_lagged.index.intersection(y_train.index)
    X_train = X_train_lagged.loc[common_train_idx]
    y_train_aligned = y_train.loc[common_train_idx]
    
    # Drop NaN
    valid_train = ~(X_train.isna().any(axis=1) | y_train_aligned.isna())
    X_train_clean = X_train[valid_train]
    y_train_clean = y_train_aligned[valid_train]
    
    if len(X_train_clean) < 10:  # Need minimum observations
        continue
    
    # X_t (predictors at time t) for forecasting r_{t+1}
    x_t = signals_clean.iloc[t:t+1]
    
    # r^{SPY}_{t+1} (actual return at time t+1)
    r_t_plus_1 = spy_clean.iloc[t+1]
    
    # Fit Neural Network model
    try:
        nn_model = MLPRegressor(hidden_layer_sizes=(50,), 
                                max_iter=500, 
                                random_state=42,
                                early_stopping=True,
                                validation_fraction=0.1)
        nn_model.fit(X_train_clean.values, y_train_clean.values)
        
        # Forecast r^{SPY}_{t+1} using X_t
        forecast = nn_model.predict(x_t.values)[0]
        
        # Null forecast: mean of training data
        null_forecast = y_train_clean.mean()
        
        # Forecast errors
        forecast_error = r_t_plus_1 - forecast
        null_error = r_t_plus_1 - null_forecast
        
        # Store results
        nn_forecast_errors.append(forecast_error)
        nn_null_errors.append(null_error)
        nn_forecast_values.append(forecast)
        nn_null_forecast_values.append(null_forecast)
        nn_actual_returns.append(r_t_plus_1)
        nn_forecast_dates.append(spy_clean.index[t+1])
        
    except Exception as e:
        if t % 50 == 0:  # Print warnings only occasionally
            print(f"Warning: NN fitting failed at t={t}: {e}")
        continue

# Convert to arrays
nn_forecast_errors = np.array(nn_forecast_errors)
nn_null_errors = np.array(nn_null_errors)

# Calculate out-of-sample R² for Neural Network
nn_sum_squared_forecast_errors = np.sum(nn_forecast_errors ** 2)
nn_sum_squared_null_errors = np.sum(nn_null_errors ** 2)

if nn_sum_squared_null_errors > 0:
    nn_r2_oos = 1 - (nn_sum_squared_forecast_errors / nn_sum_squared_null_errors)
else:
    nn_r2_oos = np.nan

print(f"\nNumber of NN OOS forecasts: {len(nn_forecast_errors)}")
print(f"Sum of squared forecast errors: {nn_sum_squared_forecast_errors:.6f}")
print(f"Sum of squared null errors: {nn_sum_squared_null_errors:.6f}")
print(f"\nNeural Network Out-of-Sample R²: {nn_r2_oos:.6f}")

if nn_r2_oos > 0:
    print(f"✓ YES - Neural Network produced a POSITIVE R²_OOS ({nn_r2_oos:.6f})")
else:
    print(f"✗ NO - Neural Network produced a NEGATIVE R²_OOS ({nn_r2_oos:.6f})")

# ============================================================================
# 2. CART (RandomForestRegressor) OOS Forecasting
# ============================================================================

print("\n" + "="*80)
print("2. CART (RandomForestRegressor) OUT-OF-SAMPLE FORECASTING")
print("="*80)

# Initialize storage for CART forecasts and errors
cart_forecast_errors = []
cart_null_errors = []
cart_forecast_values = []
cart_null_forecast_values = []
cart_actual_returns = []
cart_forecast_dates = []

# Rolling out-of-sample procedure for CART
for t in range(start_idx, T - 1):
    # Data through time t (for estimation)
    spy_train = spy_clean.iloc[:t+1]
    signals_train = signals_clean.iloc[:t+1]
    
    # Create lagged data: X_{t-1} predicts r_t
    X_train_lagged = signals_train.shift(1).iloc[1:]
    y_train = spy_train.iloc[1:t+1]
    
    # Align indices
    common_train_idx = X_train_lagged.index.intersection(y_train.index)
    X_train = X_train_lagged.loc[common_train_idx]
    y_train_aligned = y_train.loc[common_train_idx]
    
    # Drop NaN
    valid_train = ~(X_train.isna().any(axis=1) | y_train_aligned.isna())
    X_train_clean = X_train[valid_train]
    y_train_clean = y_train_aligned[valid_train]
    
    if len(X_train_clean) < 10:  # Need minimum observations
        continue
    
    # X_t (predictors at time t) for forecasting r_{t+1}
    x_t = signals_clean.iloc[t:t+1]
    
    # r^{SPY}_{t+1} (actual return at time t+1)
    r_t_plus_1 = spy_clean.iloc[t+1]
    
    # Fit CART model
    try:
        cart_model = RandomForestRegressor(n_estimators=100, max_depth=None, random_state=42)
        cart_model.fit(X_train_clean.values, y_train_clean.values)
        
        # Forecast r^{SPY}_{t+1} using X_t
        forecast = cart_model.predict(x_t.values)[0]
        
        # Null forecast: mean of training data
        null_forecast = y_train_clean.mean()
        
        # Forecast errors
        forecast_error = r_t_plus_1 - forecast
        null_error = r_t_plus_1 - null_forecast
        
        # Store results
        cart_forecast_errors.append(forecast_error)
        cart_null_errors.append(null_error)
        cart_forecast_values.append(forecast)
        cart_null_forecast_values.append(null_forecast)
        cart_actual_returns.append(r_t_plus_1)
        cart_forecast_dates.append(spy_clean.index[t+1])
        
    except Exception as e:
        if t % 50 == 0:  # Print warnings only occasionally
            print(f"Warning: CART fitting failed at t={t}: {e}")
        continue

# Convert to arrays
cart_forecast_errors = np.array(cart_forecast_errors)
cart_null_errors = np.array(cart_null_errors)

# Calculate out-of-sample R² for CART
cart_sum_squared_forecast_errors = np.sum(cart_forecast_errors ** 2)
cart_sum_squared_null_errors = np.sum(cart_null_errors ** 2)

if cart_sum_squared_null_errors > 0:
    cart_r2_oos = 1 - (cart_sum_squared_forecast_errors / cart_sum_squared_null_errors)
else:
    cart_r2_oos = np.nan

print(f"\nNumber of CART OOS forecasts: {len(cart_forecast_errors)}")
print(f"Sum of squared forecast errors: {cart_sum_squared_forecast_errors:.6f}")
print(f"Sum of squared null errors: {cart_sum_squared_null_errors:.6f}")
print(f"\nCART Out-of-Sample R²: {cart_r2_oos:.6f}")

if cart_r2_oos > 0:
    print(f"✓ YES - CART produced a POSITIVE R²_OOS ({cart_r2_oos:.6f})")
else:
    print(f"✗ NO - CART produced a NEGATIVE R²_OOS ({cart_r2_oos:.6f})")

# ============================================================================
# 3. Comparison Summary
# ============================================================================

print("\n" + "="*80)
print("COMPARISON: OOS R² ACROSS MODELS")
print("="*80)

# Get linear regression OOS R² from Section 4 if available
linear_oos_r2 = None
if 'r2_oos' in globals():
    linear_oos_r2 = r2_oos

comparison_data = []
if linear_oos_r2 is not None:
    comparison_data.append({'Model': 'Linear Regression', 'OOS R²': linear_oos_r2})
if not np.isnan(nn_r2_oos):
    comparison_data.append({'Model': 'Neural Network (MLP)', 'OOS R²': nn_r2_oos})
if not np.isnan(cart_r2_oos):
    comparison_data.append({'Model': 'CART (RandomForest)', 'OOS R²': cart_r2_oos})

if comparison_data:
    comparison_df = pd.DataFrame(comparison_data)
    print(comparison_df.to_string(index=False))

# ============================================================================
# 4. Build Trading Strategies from OOS Forecasts
# ============================================================================

print("\n" + "="*80)
print("4. TRADING STRATEGIES FROM OOS FORECASTS")
print("="*80)

# Neural Network OOS Strategy
print("\n4.1. Neural Network OOS Strategy")
print("-" * 80)

if len(nn_forecast_values) > 0:
    # Create Series with forecasts and actual returns
    nn_forecasts_series = pd.Series(nn_forecast_values, index=nn_forecast_dates)
    nn_actual_series = pd.Series(nn_actual_returns, index=nn_forecast_dates)
    
    # Align with SPY returns for strategy building
    nn_spy_aligned = spy_excess.loc[nn_forecast_dates]
    
    # Portfolio weights: w_t = 100 * r̂^{SPY}_{t+1}
    nn_weights = 100 * nn_forecasts_series
    
    # Strategy returns: r^x_{t+1} = w_t * r^{SPY}_{t+1}
    nn_oos_strategy_returns = nn_weights * nn_spy_aligned
    
    # Calculate statistics
    nn_oos_stats = calculate_strategy_stats_oos(nn_oos_strategy_returns, spy_excess)
    
    if nn_oos_stats:
        print("NN OOS Strategy Statistics:")
        for key, value in nn_oos_stats.items():
            if isinstance(value, float):
                print(f"  {key}: {value:.6f}")
            else:
                print(f"  {key}: {value}")
    else:
        print("Failed to calculate NN OOS strategy statistics")
else:
    print("No NN OOS forecasts available")
    nn_oos_strategy_returns = None
    nn_oos_stats = None

# CART OOS Strategy
print("\n4.2. CART OOS Strategy")
print("-" * 80)

if len(cart_forecast_values) > 0:
    # Create Series with forecasts and actual returns
    cart_forecasts_series = pd.Series(cart_forecast_values, index=cart_forecast_dates)
    cart_actual_series = pd.Series(cart_actual_returns, index=cart_forecast_dates)
    
    # Align with SPY returns for strategy building
    cart_spy_aligned = spy_excess.loc[cart_forecast_dates]
    
    # Portfolio weights: w_t = 100 * r̂^{SPY}_{t+1}
    cart_weights = 100 * cart_forecasts_series
    
    # Strategy returns: r^x_{t+1} = w_t * r^{SPY}_{t+1}
    cart_oos_strategy_returns = cart_weights * cart_spy_aligned
    
    # Calculate statistics
    cart_oos_stats = calculate_strategy_stats_oos(cart_oos_strategy_returns, spy_excess)
    
    if cart_oos_stats:
        print("CART OOS Strategy Statistics:")
        for key, value in cart_oos_stats.items():
            if isinstance(value, float):
                print(f"  {key}: {value:.6f}")
            else:
                print(f"  {key}: {value}")
    else:
        print("Failed to calculate CART OOS strategy statistics")
else:
    print("No CART OOS forecasts available")
    cart_oos_strategy_returns = None
    cart_oos_stats = None

# ============================================================================
# 5. Compare OOS Strategies with Linear Regression OOS Strategy
# ============================================================================

print("\n" + "="*80)
print("5. COMPARISON: OOS STRATEGIES")
print("="*80)

# Get linear regression OOS strategy stats if available
linear_oos_stats = None
if 'oos_stats' in globals():
    linear_oos_stats = oos_stats

if linear_oos_stats and nn_oos_stats and cart_oos_stats:
    print("\nMean Return (annualized):")
    print(f"  Linear Regression OOS: {linear_oos_stats['Mean (annualized)']:.6f}")
    print(f"  Neural Network OOS: {nn_oos_stats['Mean (annualized)']:.6f}")
    print(f"  CART OOS: {cart_oos_stats['Mean (annualized)']:.6f}")
    
    print("\nVolatility (annualized):")
    print(f"  Linear Regression OOS: {linear_oos_stats['Volatility (annualized)']:.6f}")
    print(f"  Neural Network OOS: {nn_oos_stats['Volatility (annualized)']:.6f}")
    print(f"  CART OOS: {cart_oos_stats['Volatility (annualized)']:.6f}")
    
    print("\nSharpe Ratio (annualized):")
    print(f"  Linear Regression OOS: {linear_oos_stats['Sharpe Ratio (annualized)']:.6f}")
    print(f"  Neural Network OOS: {nn_oos_stats['Sharpe Ratio (annualized)']:.6f}")
    print(f"  CART OOS: {cart_oos_stats['Sharpe Ratio (annualized)']:.6f}")
    
    print("\nMaximum Drawdown:")
    print(f"  Linear Regression OOS: {linear_oos_stats['Max Drawdown']:.6f}")
    print(f"  Neural Network OOS: {nn_oos_stats['Max Drawdown']:.6f}")
    print(f"  CART OOS: {cart_oos_stats['Max Drawdown']:.6f}")
    
    print("\nMarket Alpha:")
    print(f"  Linear Regression OOS: {linear_oos_stats['Market Alpha']:.6f}")
    print(f"  Neural Network OOS: {nn_oos_stats['Market Alpha']:.6f}")
    print(f"  CART OOS: {cart_oos_stats['Market Alpha']:.6f}")
    
    print("\nMarket Beta:")
    print(f"  Linear Regression OOS: {linear_oos_stats['Market Beta']:.6f}")
    print(f"  Neural Network OOS: {nn_oos_stats['Market Beta']:.6f}")
    print(f"  CART OOS: {cart_oos_stats['Market Beta']:.6f}")
    
    print("\nInformation Ratio (annualized):")
    print(f"  Linear Regression OOS: {linear_oos_stats['Information Ratio (annualized)']:.6f}")
    print(f"  Neural Network OOS: {nn_oos_stats['Information Ratio (annualized)']:.6f}")
    print(f"  CART OOS: {cart_oos_stats['Information Ratio (annualized)']:.6f}")

print("\n" + "="*80)
print("NN & CART OOS IMPLEMENTATION COMPLETE")
print("="*80)
print("\nNote: Out-of-sample performance is a more realistic assessment of model performance")
print("as it avoids look-ahead bias and overfitting issues present in in-sample analysis.")


OUT-OF-SAMPLE FORECASTING: NEURAL NETWORK & CART

Using both DP and EP as signals for forecasting
Comparing Neural Network (MLPRegressor) and CART (RandomForestRegressor)

Data range: 1996-12-31 to 2025-10-31
Total observations: 347

Starting OOS at t=60 (observation 2001-12-31 00:00:00)
Running rolling OOS procedure from t=60 to t=345...

1. NEURAL NETWORK (MLPRegressor) OUT-OF-SAMPLE FORECASTING


c:\Users\cat33\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\cat33\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\cat33\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\cat33\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\cat33\anaconda3\Lib\site-packages\sklearn\neural_network\_multi


Number of NN OOS forecasts: 286
Sum of squared forecast errors: 0.647437
Sum of squared null errors: 0.661497

Neural Network Out-of-Sample R²: 0.021255
✓ YES - Neural Network produced a POSITIVE R²_OOS (0.021255)

2. CART (RandomForestRegressor) OUT-OF-SAMPLE FORECASTING

Number of CART OOS forecasts: 286
Sum of squared forecast errors: 0.752961
Sum of squared null errors: 0.661497

CART Out-of-Sample R²: -0.138269
✗ NO - CART produced a NEGATIVE R²_OOS (-0.138269)

COMPARISON: OOS R² ACROSS MODELS
               Model    OOS R²
   Linear Regression  0.088220
Neural Network (MLP)  0.021255
 CART (RandomForest) -0.138269

4. TRADING STRATEGIES FROM OOS FORECASTS

4.1. Neural Network OOS Strategy
--------------------------------------------------------------------------------
NN OOS Strategy Statistics:
  Mean (annualized): 0.265448
  Volatility (annualized): 0.357648
  Sharpe Ratio (annualized): 0.742206
  Max Drawdown: -0.944710
  Market Alpha: 0.006137
  Market Beta: -2.003657
  Inf